### ISSUE TITLE
TypeError: globe.getGlobeRadius is not a function

### ISSUE THREAD

**Issue by Fullstack-WEB-Blockchain-Developer** [vasturiano/react-globe.gl#104]
**Describe the bug**
Please check this screenshot
I have use only this example with nextjs and typescript
https://github.com/vasturiano/react-globe.gl/blob/master/example/clouds/index.html

What's wrong with using this utility in nextjs?

**Screenshots**
![image](https://user-images.githubusercontent.com/86783082/199402448-b9cffd6a-dd01-42c2-9823-c5fb5a97252c.png)

**Desktop (please complete the following information):**
 - OS: window10
 - Browser chrome
 - Version 107

**Comment by vasturiano** [comment]
@Fullstack-WEB-Blockchain-Developer thanks for reaching out.

That looks like a typescript error, but that method is declared:
https://github.com/vasturiano/react-globe.gl/blob/3fdfe0c582aaf28d2656035b8e54c3152f888098/src/index.d.ts#L261

Best would be if you could post an online example, if you're still having trouble.

**Comment by Fullstack-WEB-Blockchain-Developer** [comment]
Thank you I have solved

**Comment by Fullstack-WEB-Blockchain-Developer** [comment]
@vasturiano Thank you for your reply.
I have fixed like this but I got still this error
![image](https://user-images.githubusercontent.com/86783082/200106428-3d6a69b6-48f5-4bfd-80b1-ed183181f722.png)

**Comment by vasturiano** [comment]
@Fullstack-WEB-Blockchain-Developer I've just updated the type definitions to include the full object spec from Three's orbit controls.
