### ISSUE TITLE
Cannot import react-globe.gl

### ISSUE THREAD

**Issue by cekcreator** [vasturiano/react-globe.gl#109]
**Describe the bug**
Trying to use the module in my react app and when trying to import "import Globe from 'react-globe.gl' ", throws an error when imported and when trying to use it. 
 
**To Reproduce**
add in "import Globe from 'react-globe.gl' "

I looked in my pkg.json to see if react-globe is in there and it is along with 'three' and the other needed react dependencies.

**Comment by vasturiano** [comment]
@cekcreator thanks for reaching out. Could you please provide a simple example that reproduces your issue in https://codesandbox.io?

**Comment by cekcreator** [comment]
Yeah ofc, after researching it may be a node problem. I create a react app using "npx create-react-app tutorial" then add the import statement. Heres a snippet.
 
`import React from 'react';
import ReactDOM from 'react-dom/client';
import './index.css';
import App from './App';
import reportWebVitals from './reportWebVitals';
import Globe from 'react-globe.gl'`

this throws me this 

"Module not found: Error: Can't resolve 'react-globe.gl' in 'C:\Users\CalebKumar\Documents\code\dash_practice\tutorial\src'"

**Comment by NikooDev** [comment]
Same problem with dynamic import from NextJS :

const Contact = Dynamic(() => import('@App/components/section/contact'), { ssr: false })

Contact component :
<img width="956" alt="Capture d’écran 2023-02-07 à 02 02 40" src="https://user-images.githubusercontent.com/43614012/217121545-32ff0876-10e5-406f-af6b-850aaadd7ad2.png">

**Comment by pieshop** [comment]
Had the same issue. Installing v2.22.0 works however.

npm install react-globe.gl@2.22.0

**Comment by stevenqzhang** [comment]
@pieshop thanks a lot, that did the trick for me!

**Comment by YChebotaev** [comment]
Same issue here

**Comment by afonsojramos** [comment]
Same here!! 

Here's the PR that is giving me the error if it helps https://github.com/afonsojramos/afonsojramos.me/pull/88

**Comment by CyberCyclone** [comment]
This happened to me to. I had version 2.22.1 working for a long time until I started having issues last week. Turned out that removing the micro updates `^2.22.1` -> `2.22.1` fixed it for me.

**Comment by afonsojramos** [comment]
> This happened to me to. I had version 2.22.1 working for a long time until I started having issues last week. Turned out that removing the micro updates `^2.22.1` -> `2.22.1` fixed it for me. 

Fixing the version to a previous one isn't exactly a fix 😅

**Comment by OmerAvital** [comment]
I think it's because in the package.json is missing the `.gl` in the exports
```json
"exports": {
    "umd": "./dist/react-globe.min.js",
    "default": "./dist/react-globe.mjs"
  },
```
instead it should be
```json
"exports": {
    "umd": "./dist/react-globe.gl.min.js",
    "default": "./dist/react-globe.gl.mjs"
  },
```

**Comment by vasturiano** [comment]
Good catch @OmerAvital.
The export endpoints have now been fixed. You shouldn't experience the issue any longer when upgrading to `v2.23.2`.

**Comment by charlierdm** [comment]
I had this issue using `v2.27.2` and had to manually dynamically import it into my react app.

I wanted to share this in case anyone hits the same issue.

```
const Globe = typeof window !== 'undefined' ? require('react-globe.gl').default : () => null
```
