### ISSUE TITLE
Enabling Touch Events

### ISSUE THREAD

**Issue by RVerma90** [vasturiano/react-globe.gl#11]
First of all, thanks for creating a great library! 

I wanted to try this library on mobile devices, but can't seem to get touchevents to work.
Would you happen to have a suggestion as to how this might be possible?

Look forward to hearing from you!

**Comment by vasturiano** [comment]
@RVerma90 thanks for reaching out.

I just added support (from `v2.9.0`) for touch events in the objects interactions. Let me know if that works for you.

**Comment by wathigo** [comment]
Thank you! It works like a charm @vasturiano

**Comment by RVerma90** [comment]
Hey @vasturiano, thanks for taking the time to add the feature :)

Unfortunately I haven't been able to get it to work, it should work with onPolygonClick right?
Is that how you did it @wathigo?

I've also realised that when build the project with create-react-app's 'yarn build', it seems to give me the following issue I've not seen before:
`Face needs to be an instance of THREE.Face3.`

`Uncaught TypeError: Cannot read property 'x' of undefined`

Any guidance would be greatly appreciated! I'll try to find other avenues for getting this to work!

Thanks again.

**Comment by vasturiano** [comment]
@RVerma90 yes you can use it with `onPolygonClick` (that is if you're using the polygons layer).

Are you on the latest module version?
Does your example work with a mouse but not touch events?
Does this polygons example work for you? https://vasturiano.github.io/react-globe.gl/example/choropleth-countries/

I'm not able to reproduce the `Face3` error when building this module locally. Not certain where the problem may lie, perhaps something related to the dependency tree. It's a long shot, but do you have multiple versions of `Three` in your dependency tree?

**Comment by RVerma90** [comment]
Hey @vasturiano !

Thanks again for the pointer!
I have been able to the link you provided to work.

I was in the middle of swapping another library react-globe for this one on a small leftover package and I think there was some leftover packages that may have caused the issue! I've got it to work now, so the long shot suggestion worked!

Thanks a lot!
