### ISSUE TITLE
Arc paths don't render if Globe component is remounted

### ISSUE THREAD

**Issue by rohanbhangui** [vasturiano/react-globe.gl#113]
**Describe the bug**
Arcs created via `arcData` show up on initial load but disappear when the Globe component is remounted. Things like locations and points don't have this issue. https://codesandbox.io/s/throbbing-leaf-lic79u?file=/src/App.tsx:1662-1866

(Note: for the sandbox, might have to turn to North American where the arcs are)

**To Reproduce**
1. Create a globe with arcData 
2. Trigger an unmount (conditional render via a button click)
3. Trigger mount
4. Arcs don't get rendered

**Expected behavior**
Arcs should be visible and available

**Additional context**
Location and Point data seem to remount correctly.

**Comment by vasturiano** [comment]
@rohanbhangui same as in https://github.com/vasturiano/react-globe.gl/issues/25.
Disabling strict mode makes the issue disappear.

**Comment by rohanbhangui** [comment]
@vasturiano Thanks, just seems curious that strict mode is the cause for it to not rerender.
