### ISSUE TITLE
Restricting Min and Max Zoom

### ISSUE THREAD

**Issue by SDineshKumarCogoport** [vasturiano/react-globe.gl#115]
I couldn't restrict the min and max zoom through Orbit Controls.
In the documentation, it was mentioned that those methods are only available for Orthographic camera.
How to change the default perspective camera to Orthographic or Is there a way to control min and max zoom in the Perspective camera?

**Comment by vasturiano** [comment]
@SDineshKumarCogoport you should use instead [maxDistance](https://threejs.org/docs/#examples/en/controls/OrbitControls.maxDistance) and [minDistance](https://threejs.org/docs/#examples/en/controls/OrbitControls.minDistance).

Those two functions take distances in ThreeJS units. If you need it relative to the globe size you can use the globe method [getGlobeRadius](https://github.com/vasturiano/react-globe.gl#utility) to multiply it by. For example:
```js
globeRef.current.controls().maxDistance = globeRef.current.getGlobeRadius() * 4;
```

**Comment by SDineshKumarCogoport** [comment]
Thanks for the solution @vasturiano 👍.  I have used this way to customize many parameters. Thanks again!
