### ISSUE TITLE
Couldn't render Alpha Colors

### ISSUE THREAD

**Issue by SDineshKumar7693** [vasturiano/react-globe.gl#116]
I have assigned colours with alpha value to hexTopColor and hexSideColor. But I couldn't get the result after the render.

I have set alpha true in the renderer as well

`globeMethods?.renderer().alpha =true;`

<img width="633" alt="Screenshot 2023-02-17 at 7 57 45 PM" src="https://user-images.githubusercontent.com/85097396/219682429-f9eb3889-068b-4f4d-a539-399430771d36.png">

```
                         <Globe
				width={480}
				height={480}
				ref={globeGL}
				waitForGlobeReady
				backgroundColor={GLOBE_COLORS[colorMode].bg}
				atmosphereColor={GLOBE_COLORS[colorMode].atmos}
				animateIn
				showAtmosphere
				atmosphereAltitude={0.10}
				globeImageUrl={TEXTURES[colorMode].one}

				hexPolygonsData={primaryCountries.features}
				hexPolygonResolution={3}
				hexPolygonMargin={0.5}
				hexPolygonColor={() => `${GLOBE_COLORS[colorMode].hex}`}
				hexPolygonCurvatureResolution={6}

				hexBinPointsData={pointBinData}
				hexAltitude={0.1}
				hexBinResolution={2}
				hexTopColor={() => "rgba(114, 120, 173, 0.2)"}
				hexSideColor={() => "rgba(114, 120, 173, 0.2)"}
				hexBinMerge={true}
				enablePointerInteraction={true}

			/>

```

**Comment by vasturiano** [comment]
@SDineshKumar7693 thanks for reaching out.

This is because you have `hexBinMerge={true}`. Transparent materials is not possible in merged geometries. If you switch of the merge, the alpha portion of the colors should start having an effect.
