### ISSUE TITLE
[bug] onLabelClick when set width and height

### ISSUE THREAD

**Issue by davidlefrancq** [vasturiano/react-globe.gl#12]
**Describe the bug**
Hi @vasturiano. Thanks for this very good library. I have one problem. When i use react-globe.gl/example/moon-landing-sites in my React Project, i set "onLabelClick = { (d) => console.log(d) }". It work normaly. But when i set attributes "width" and "height" of Globe at value 400 for exemple, the onLabelClick don't work. Have you un idee where have the problem ?

**To Reproduce**
In exemple "react-globe.gl/example/moon-landing-sites" :
1. Set width and height attributes of Globe at 400.
2. Start projet and go to web page.
2. Click on "Apolo 15", "Luna 2" or other.
4. See that nothing execute click event.

**Expected behavior**
Normally, a click event start. In the original example, a new page is open.

**Desktop (please complete the following information):**
 - OS: [Windows 10]
 - Browser [Firefox 79, Chrome 84]
 - Version [2.12.2]

**Comment by vasturiano** [comment]
@davidlefrancq thanks for the report.

I've just created a sandbox of the same example with set width/height of `400` and seems to work fine:
https://codesandbox.io/s/moon-with-width-height-fij3l

Are you able to reproduce the issue there?

**Comment by davidlefrancq** [comment]
Good idea the sandbox. I have found the origin of my problem. I put a Globe in a Div with "text-align = center". That's when it doesn't work anymore. I will be able to solve my problem with for exemple : 

Div.style = width: 400px, height:400px, textAlign: left, marginLeft: auto, marginRight: "auto"

Thank you very much for your help.
