### ISSUE TITLE
SyntaxError: The requested module '@tweenjs/tween.js' does not provide an export named 'default'

### ISSUE THREAD

**Issue by vdeva** [vasturiano/react-globe.gl#126]
**Describe the bug**
In nextjs I get this error:
Server Error

SyntaxError: The requested module '@tweenjs/tween.js' does not provide an export named 'default'
This error happened while generating the page. Any console logs will be displayed in the terminal window.
Call Stack
<unknown>
file:project/node_modules/three-globe/dist/three-globe.mjs (3)
ModuleJob._instantiate
node:internal/modules/esm/module_job (124:21)
async ModuleJob.run
node:internal/modules/esm/module_job (190:5)

**To Reproduce**
1. npm i react-globe.gl
2. import Globe from 'react-globe.gl';
3. In a page return do:
```
<div>
  <Globe
  backgroundColor="rgba(0,0,0,0)"
  showGlobe={false}
  showAtmosphere={false}
  />,
</div>
```
**Expected behavior**
For things to work

**Additional context**
I have no idea why this is happening

**Comment by sergeykcommpeak** [comment]
I guess this component can't run in server env. 
Try importing Globe this way: 
`const Globe = dynamic(() => import("@/components/Globe"), {
	ssr: false,
});`

**Comment by vdeva** [comment]
not sure how to implement that

**Comment by vdeva** [comment]
> I guess this component can't run in server env. Try importing Globe this way: `const Globe = dynamic(() => import("@/components/Globe"), { ssr: false, });`

hey thanks actually that got it working :)

**Comment by McEazy2700** [comment]
Hi I'm following the quick start on the npm docs, and I'm getting this same error
```typescript
 import Globe from "react-globe.gl";

const Home: NextPageWithLayout = () => {
    const { loading, data } = usePopularPosts({ first: 4 })

    if (loading) return <PageLoadingRing />;
    const posts = (data?.posts && data.posts.edges.length > 3) ? data.posts : dummyPosts.posts;

    return (
        <>
            <Head>
                <title>GeoTech</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <main >
                <Globe />
                <PodcastLanding />
                <BlogLanding posts={posts} />
            </main>
        </>
    )
}

```

and I get this error
```bash
error - file:///home/eazy/Documents/dev/works/geotech/geo-tech-ui/node_modules/three-globe/dist/three-globe.mjs:3
import TWEEN from '@tweenjs/tween.js';
       ^^^^^
SyntaxError: The requested module '@tweenjs/tween.js' does not provide an export named 'default'

```

**Comment by vdeva** [comment]
try importing it the way [sergeykcommpeak](https://github.com/sergeykcommpeak) suggested it
worked out for me
