### ISSUE TITLE
Adding option to have opacity/gradient color in the points layer and hex bin layer

### ISSUE THREAD

**Issue by BangNguyen1992** [vasturiano/react-globe.gl#137]
**Is your feature request related to a problem? Please describe.**
I want to re-create the 3D globe on GitHub, I try to use the points layer and hex bin layer to display the spike out of the globe. I have tried it with rgba color but it doesn't work
```js
hexSideColor={() => 'rgba(255, 255, 255, 0.1)'}
or
pointColor={() => 'rgba(255, 255, 255, 0.1)'}
```

<img width="841" alt="image" src="https://github.com/vasturiano/react-globe.gl/assets/15904835/fe4a7e19-036f-4d2d-94c7-47a4800032cb">

**Describe the solution you'd like**
- Adding the option to have opacity/gradient color in the points layer and hex bin layer would be great.
- Or any other suggestions are welcome

Thank you.

**Comment by vasturiano** [comment]
@BangNguyen1992 do you perhaps have `pointsMerge={true}` and/or `hexBinMerge={true}`?

Merging the objects in a layer can have more efficient rendering performance, but does not support opacity on the objects. So it's a trade-off.

**Comment by BangNguyen1992** [comment]
Hello @vasturiano, thank you for your quick reply.

It's my mistake, I have set them to true before to improve performance but forgot to turn them off.

Again, thank you very much.
