### ISSUE TITLE
[Suggestion/Need help]: Fill the surface with dots (or other shapes) then Group them by country

### ISSUE THREAD

**Issue by BangNguyen1992** [vasturiano/react-globe.gl#139]
**Is your feature request related to a problem? Please describe.**

1. I want to wrap the globe with a dots layer, it would be similar to a hexed polygon layer but with a rounded shape instead of a hexagon
2. If possible, it can be config with different shapes

I am quite new to the THREE.js so I am not that good in 3D objects yet, so any guide or tutorial on how to achieve the solution is welcome.

**Describe the solution you'd like**
- The new layer (dots layer) would be similar to a hexed polygon layer but with a rounded shape instead of a hexagon.

**Describe alternatives you've considered**
- I haven't tried with the custom layer yet so I am not sure if it would give me the correct result

**Additional context**
- Similar to what Stripe was doing https://stripe.com/blog/globe
- Or the codepen here https://codepen.io/emave/pen/WKNQOo

The Github globe would be what I want to achieve in the end

<img width="975" alt="image" src="https://github.com/vasturiano/react-globe.gl/assets/15904835/8c72a946-3653-4381-b866-397206e3c577">

Thank you!

**Comment by BangNguyen1992** [comment]
Hello @vasturiano, Thank you for the quick reply.

Yes, I have tried it, I changed it from 0.7 to 0.75, and it looks much better now. However, when I zoom in to `altitude: 0.5`, I begin to see the hexagon clearly.


With hexPolygonMargin 0.7:
<img width="719" alt="image" src="https://github.com/vasturiano/react-globe.gl/assets/15904835/a0ee2fc0-b58e-43cf-bf60-fe251abd3ad4">

When zoom-in
<img width="994" alt="image" src="https://github.com/vasturiano/react-globe.gl/assets/15904835/946ee818-c66b-4d83-80cc-fb7c0e3d751d">


With hexPolygonMargin 0.75:
<img width="666" alt="image" src="https://github.com/vasturiano/react-globe.gl/assets/15904835/bd10ee6a-ec7a-4935-9409-36b785ca06f2">

When zoom-in
<img width="1072" alt="image" src="https://github.com/vasturiano/react-globe.gl/assets/15904835/31015371-161f-44b3-baae-67dc497efb0e">


PS: If there is no quick solution, I think this is an okay result. However, I just want to elaborate on the solution a bit, do you have any suggestions to achieve a different shape? Might be using a custom layer, or threejs object like this codepen.

https://codepen.io/emave/pen/WKNQOo

**Comment by vasturiano** [comment]
You could potentially do it in a custom layer. Currently it's mainly a combination of functionality from [h3-js](https://github.com/uber/h3-js) for the hex layout computation, and the rendering of conic ThreeJS objects using [three-conic-polygon-geometry](https://github.com/vasturiano/three-conic-polygon-geometry). These conic object surfaces have hexagon shapes in geojson format, as defined by h3-js.

Here is the relevant portion of the code in the `three-globe` module:
https://github.com/vasturiano/three-globe/blob/d8eba6ee5fd2344deb870a4db55285a0d743674e/src/layers/hexedPolygons.js#L99-L144

**Comment by BangNguyen1992** [comment]
Thank you @vasturiano, I will look more into it

**Comment by vasturiano** [comment]
@BangNguyen1992 just to let you know that I've recently added functionality that allows to have the polygon points as circular dots. You just need to add `hexPolygonUseDots={true}` (disabled by default), in the [hexed polygons layer](https://github.com/vasturiano/react-globe.gl#hexed-polygons-layer).

And [here's an example](https://vasturiano.github.io/react-globe.gl/example/hexed-polygons/) of what it looks like.

**Comment by BangNguyen1992** [comment]
@vasturiano That's great, thank you very much

**Comment by tyn1998** [comment]
Hello @BangNguyen1992, the blue globe with white dots and lightblue atmosphere around it looks great and currently I also want to implement a globe just like GitHub's :)

I'm new to globe.gl and 3D world and I'm eager to learn. Would you mind providing a code snippet for your globe?

![image](https://github.com/vasturiano/react-globe.gl/assets/32434520/0ff64551-7991-45bd-9b3d-9a911315199f)
