### ISSUE TITLE
Limiting Framerate

### ISSUE THREAD

**Issue by MichaelBonnet** [vasturiano/react-globe.gl#143]
I have an app that is based on the [Satellites example](https://github.com/vasturiano/react-globe.gl/blob/master/example/satellites/index.html). I want to be able to control how quickly things move forward, by essentially controlling what multiple of "real time" is used to generate the next frame. For example, I could have a dropdown where a user selects "5", and then things move at 5x real speed. My first thought is to simply control the value of `TIME_STEP` in the example so as to control the incrementation of `time` per frame. However, to be reliable, that would require controlling the framerate as well.

Is there a way to artificially limit the number of frames generated in a timespan, say, in one second?

**Comment by vasturiano** [comment]
@MichaelBonnet if you want to run slower than the framerate you can set a delay in your frame ticker. Something like:

```js
setTimeout(() => requestAnimationFrame(frameTicker), numMs)
```

The `numMs` would depend on your desired frame rate, and how long it has elapsed since the previous frame.
