### ISSUE TITLE
Bug: Adding data to hexPolygonsData from local json cause losing part of the animationIn

### ISSUE THREAD

**Issue by BangNguyen1992** [vasturiano/react-globe.gl#144]
**Describe the bug**
Adding data to hexPolygonsData from local JSON causes losing part of the animation where the globe scaling

https://codesandbox.io/s/stoic-davinci-qt5gzv?file=/src/Globe.tsx:186-222

**To Reproduce**
1. Render the globe
2. Add data to the `hexPolygonsData` prop
3. Refresh the page
4. The globe suddenly appears without any scaling animation

**Expected behavior**
- The globe should have scaling animation like before adding the `hexPolygonsData`

**Screenshots**
https://codesandbox.io/s/stoic-davinci-qt5gzv?file=/src/Globe.tsx:186-222

**Desktop (please complete the following information):**
 - OS: MacOS Monterey 12.4
 - Browser: Chrome 115.0.5790.170

**Comment by vasturiano** [comment]
@BangNguyen1992 it helps if you add a globe image via `globeImageUrl`. Because in that case the initialization will wait until that asset is fetched before performing the build-in animation.

**Comment by BangNguyen1992** [comment]
Hello @vasturiano, thank you for your suggestion.

However, in my case, I am using the `globeMaterial` already so I dont need the `globeImageUrl`.

Furthermore, adding `globeImageUrl` just to delay the initialization without actually using it seems weird to me. It will cost more resources, reduce performance, and not always work when I test. 😞 

Is there any other ways to resolve it?

**Comment by vasturiano** [comment]
You could cancel the built-in animation, via `animateIn={false}` and then build your own. The rotation would be as simple as pointing the camera at `lng: 90` and then animating it to `lng:  0` after the data is set. This can be done with the `pointOfView` method, and it even supports a transition time.

**Comment by BangNguyen1992** [comment]
Thank you @vasturiano
