### ISSUE TITLE
Ref missing when using dynamic import in Nextjs

### ISSUE THREAD

**Issue by benjaminlim00** [vasturiano/react-globe.gl#15]
**Describe the bug**
Hi i am building a globe using the library in NextJs, and due to: https://github.com/vasturiano/react-globe.gl/issues/1
I am dynamically importing the library to prevent SSR, in this manner:
`const Globe = dynamic(import('react-globe.gl'), { ssr: false });`

However when I do so, the ref pointing to the globe is missing and I am unable to call:
`GlobeEl.current.controls().autoRotate = true;
 Globe.current.controls().autoRotateSpeed = 0.1;`
where
`const GlobeEl = useRef()`
and 
` ref={globeEl}`
is passed into Globe,

as shown in the example of  https://github.com/vasturiano/react-globe.gl/blob/master/example/world-population/index.html
as current is undefined. 

Is there a way to me to pass on the ref that was originally attached? Maybe using React.forwardRef or something

**Comment by benjaminlim00** [comment]
Just to update, i have tried https://github.com/vercel/next.js/issues/4957
but that does no resolve the issue, I still get

![Screenshot from 2020-10-13 22-28-19](https://user-images.githubusercontent.com/36101433/95874398-6fb69880-0da3-11eb-9d5c-b34dfb6a6fd9.png)

Here is my code:
`//https://github.com/vasturiano/react-globe.gl/issues/1
import dynamic from 'next/dynamic';
import { useEffect, useState, useRef } from 'react';
import ExchangesHelpers from '../lib/exchanges';
import { getCurrencies } from './api/exchange/switchainHelpers';
import { COUNTRIES_DATA } from '../data/countries_data';
import HEX_DATA from '../data/countries_hex_data.json';

const GlobeWithoutRef = dynamic(import('react-globe.gl'), { ssr: false });
const Globe = React.forwardRef((props, ref) => (
  <GlobeWithoutRef {...props} forwardedRef={ref} />
));

const getRandomCountry = () => {
  return COUNTRIES_DATA[Math.floor(Math.random() * COUNTRIES_DATA.length)];
};

export default function Home() {
  const globeEl = useRef();
  const [currencies, setCurrencies] = useState();
  const country = getRandomCountry();
  const [countriesData, setCountriesData] = useState([
    {
      lat: country.latitude,
      lng: country.longitude,
      label: `${country.name} (BTC-ETH)`, //maybe change this
    },
  ]);
  const [hex, setHex] = useState({ features: [] });

  useEffect(() => {
    setHex(HEX_DATA);
  }, []);

  useEffect(() => {
    (async () => {
      const res = await getCurrencies();
      setCurrencies(res.result.currencies);
    })();
  }, []);

  const getRandomPair = () => {
    if (currencies) {
      const from = currencies[Math.floor(Math.random() * currencies.length)];
      const remainderCurrencies = currencies.filter((item) => item !== from);
      const to =
        remainderCurrencies[
          Math.floor(Math.random() * remainderCurrencies.length)
        ];
      return `${from} - ${to}`;
    }
  };

  useEffect(() => {
    let interval;
    if (currencies) {
      let prevTransaction;
      interval = setInterval(() => {
        (async () => {
          const latestTransactions = await ExchangesHelpers.getLatestTransactions();
          const country = getRandomCountry();
          if (
            prevTransaction === latestTransactions.result.transactions[0].id
          ) {
            const pair = getRandomPair();
            console.log('same data,faking transaction');
            setCountriesData([
              {
                lat: country.latitude,
                lng: country.longitude,
                label: `${country.name} (${pair})`,
              },
            ]);
          } else {
            const transactionData = latestTransactions.result.transactions[0];
            console.log('new data');
            setCountriesData([
              {
                lat: country.latitude,
                lng: country.longitude,
                label: `${country.name} (${transactionData.pair})`,
              },
            ]);
          }
          prevTransaction = latestTransactions.result.transactions[0].id;
        })();
      }, 3000); //Every 3 seconds
    }
    return () => {
      if (interval) {
        clearInterval(interval);
      }
    };
  }, [currencies]);

  useEffect(() => {
    globeEl.current.controls().autoRotate = true;
    globeEl.current.controls().autoRotateSpeed = 0.1;
  }, []);

  return (
    <Globe
      ref={globeEl}
      globeImageUrl="/globe.png"
      backgroundImageUrl="/gradient.jpg"
      labelsData={countriesData}
      labelText={'label'}
      labelSize={1.7}
      labelColor={() => 'white'}
      labelDotRadius={0.4}
      labelAltitude={0.05}
      hexPolygonsData={hex.features}
      hexPolygonResolution={3} //values higher than 3 makes it buggy
      hexPolygonMargin={0.62}
      hexPolygonColor={() => '#1b66b1'}
    />
  );
}
`

**Comment by vasturiano** [comment]
@benjaminlim00 this appears more related to `nextjs` than specific to `globe.gl` so perhaps they have better advice on how to go about solving it.
Have you tried the approach in which your whole component (that includes the globe component ref) is wrapped in a dynamic import?

**Comment by benjaminlim00** [comment]
I fixed this issue by this code:

let Globe = () => null;
if (typeof window !== 'undefined') Globe = require('react-globe.gl').default;

**Comment by pojntfx** [comment]
I also ran into this problem; the solution above worked in dev but not prod modes (threw document errors for me). Here is how I fixed it, using `forwardRef`: https://github.com/pojntfx/webnetesctl/blob/main/components/globe.tsx and https://github.com/pojntfx/webnetesctl/blob/main/pages/index.tsx

**Comment by jacobhoekert** [comment]
@pojntfx I have not gone into prod mode yet, so I am curious about your forwardRef solution. I am confused by your links -- the code in the second link above does not contain anything about the globe?

**Comment by pojntfx** [comment]
@jacobhoekert Sorry, due to some heavy refactoring the relevant source has moved, here are the new links:

- https://github.com/alphahorizonio/webnetesctl/blob/main/components/pages/overview.tsx#L240-L296 (actual `<Globe />` usage)
- https://github.com/alphahorizonio/webnetesctl/blob/main/components/globe.tsx (wrapper)
- https://github.com/alphahorizonio/webnetesctl/blob/main/components/pages/overview.tsx#L728-L735 (dynamic imports)

You can also see it in action here: https://webnetes.dev/ (enter something like `1.2.3` in the "New Cluster ID" input and click on "create cluster" which should show the globe)

**Comment by stevenqzhang** [comment]
Unfortunately @pojntfx I couldn't get your `forwardRef` suggestion to work, but @benjaminlim00 's solution worked. Thanks all!

**Comment by Bawanthathilan** [comment]
> Unfortunately @pojntfx I couldn't get your `forwardRef` suggestion to work, but @benjaminlim00 's solution worked. Thanks all!

can you share your code example

**Comment by gty3** [comment]
I was able to get @pojntfx example working with the use of 'onGlobeReady' to access the globe ref in useEffect without errors. Works well in production.

- https://github.com/gty3/geoffreyoung/blob/main/app/components/globeWrapper.tsx - wrapper
- https://github.com/gty3/geoffreyoung/blob/main/app/components/world.tsx - globe

**Comment by Nerfi** [comment]
In case someone runs into the same issue of Hydration or not being able to access the ref, here is the full code 

``` "use client";
import { useState, useEffect, useRef, forwardRef } from "react";
import dynamic from "next/dynamic";
//data 
import arcData from "../pages/contact/travelArcData.json";
import travelHistory from "../pages/contact/flighstsDAta.json";

const GlobeTmpl = dynamic(() => import("./globe"), {
  ssr: false,
});
const Globe = forwardRef((props, ref) => (
  <GlobeTmpl {...props} forwardRef={ref} />
));

const World = () => {
  const globeRef = useRef();
  const earthImg = "//unpkg.com/three-globe/example/img/earth-night.jpg";
  const backGroundImg = "//unpkg.com/three-globe/example/img/night-sky.png";

  const [globeReady, setGlobeReady] = useState(false);

  const startTime = 1000;

  useEffect(() => {
    if (!globeRef.current) {
      return;
    }
    globeRef.current.pointOfView(
      {
        lat: 39.609913,
        lng: -105.962477,
        altitude: 2.5,
      },
      startTime
    );
    // globeRef.current.controls().enableZoom = false;
    // Auto-rotate
    globeRef.current.controls().autoRotate = true;
    globeRef.current.controls().autoRotateSpeed = 1;
  }, [globeReady]);

  return (
    <>
      <Globe
        globeImageUrl={earthImg}
         ref={globeRef}
        backgroundImageUrl={backGroundImg}
        onGlobeReady={() => setGlobeReady(true)}
        backgroundColor="rgba(0,0,0,0)"
        // height={500}
        hexPolygonMargin={0.7}
        hexPolygonColor={() => "rgba(255, 255, 255, 1)"}
        showAtmosphere={true}
        animateIn={true}
        arcsData={arcData.flights}
         arcDashAnimateTime={180}
         arcDashLength={150}
         arcDashGap={250}
         arcColor={() => ["red", "blue", "yellow"]}
         //label
         labelsData={travelHistory.airports}
         labelColor={() => "#D5FFD0"}
         labelSize={0.5}
         labelDotRadius={0.4}
         labelResolution={6}
       
      />
    </>
  );
};

export default World;
```

**Comment by rafaelcruzazevedo** [comment]
Anyone can help? `ref?.current` there's nothing! No methods in **ref** 🤔 
```tsx
/**
 * `Globe` component.
 */

const ReactGlobe = dynamic(() => import('react-globe.gl'), { ssr: false });

/**
 * Export `Globe3D` component.
 */

export const Globe3D = () => {
  const ref = useRef<GlobeMethods>();
  const gData = [...Array(35).keys()].map(() => ({
    country: 'Portugal',
    description: 'Healthcare; Fintech; Gaming; Blockchain',
    lat: (Math.random() - 0.5) * 180,
    lng: (Math.random() - 0.5) * 360
  })) as Data[];

  return (
    <Wrapper>
      <ReactGlobe
        globeImageUrl={'//unpkg.com/three-globe/example/img/earth-blue-marble.jpg'}
        htmlElement={(content: any) => {
          const elem = document.createElement('div');

          elem.classList.add('globe-marker');
          elem.ariaLabel = content.country;
          elem.style.cursor = 'pointer';
          elem.style.pointerEvents = 'auto';
          elem.innerHTML = `
            <div class="globe-marker-point"></div>
            <div class="globe-marker-tooltip" active="false">
              <strong>${content.country}</strong>
              <p>${content.description}</p>
            </div>
          `;

          elem.addEventListener('click', () => {
            const elements = document.querySelectorAll('.globe-marker');
            
            elements.forEach(element => {
              element.classList.remove('active');
            });

            elem.classList.toggle('active');
            // ref.current?.pointOfView({ lat: content.lat, lng: content.lng }, 1000);
          });

          return elem;
        }}
        htmlElementsData={gData}
        ref={ref}
        
        showAtmosphere={false}
      />
    </Wrapper>
  );
};
```

**Comment by dhirajbajaj** [comment]
2024 and this issue remains; next js needs a version for this;
