### ISSUE TITLE
Bug: The atmosphere become white or disappear when set color for atmosphereColor

### ISSUE THREAD

**Issue by BangNguyen1992** [vasturiano/react-globe.gl#153]
**Describe the bug**
- The atmosphere of the globe is white or disappears when I set the color for atmosphereColor

**To Reproduce**
1. Create a globe
2. Set value for atmosphereColor
3. If the color is `0x3a228a` format -> the atmosphere becomes white
4. If the color is `#3a228a` -> atmosphere disappears

**Expected behavior**
- The atmosphere color should not disappear or change to white

**Screenshots**

**Additional context**
- I have tried wrapping the color with `THREE.Color("#3a228a")` but not successful

**Comment by vasturiano** [comment]
@BangNguyen1992 this should be working properly. The thing here is that the color you chose for the atmosphere is very similar to the background color so the difference is nearly invisible. If you increase the `atmosphereAltitude={1}` you'll notice that it's there although faint.

As for the white color, you might be passing the numeric color as a string, like `atmosphereColor="0x3a228a"`? That would be incorrect, you should pass it as a number: `atmosphereColor={0x3a228a}`.

Also passing a `THREE.Color` object won't work, that was never supported.

**Comment by BangNguyen1992** [comment]
I see, thank you for your reply
