### ISSUE TITLE
Full size globe

### ISSUE THREAD

**Issue by mighty-phoenix** [vasturiano/react-globe.gl#156]
I want to make the globe full size... There should be no gap between the globe and the screen...(in case width is smaller than height, make width diameter, otherwise make height diameter.
Kindly help me accomplish this.
Quick response would be highly appreciated.
Thanks!

**Comment by vasturiano** [comment]
@mighty-phoenix you can just adjust the alitude of the pov camera to achieve this. Like it's done here using the `pointOfView` method:
https://github.com/vasturiano/react-globe.gl/blob/b663b9e69fa7cc5a24e8598a5d15a41ea39ff5cc/example/custom-layer/index.html#L43

A value of `1.38` seems to achieve a fit height wise.

**Comment by mighty-phoenix** [comment]
Thanks a ton! @vasturiano 
Works like a charm.

**Comment by mighty-phoenix** [comment]
For anyone who wants to achieve this without cutting off the drop-shadow, you can use an altitude of `1.66`
Thanks!
