### ISSUE TITLE
Defining speed of auto rotation

### ISSUE THREAD

**Issue by idjuradj** [vasturiano/react-globe.gl#158]
Can someone clarify to me in which units is the `autoRotateSpeed`?
For example, if I want one full rotation of the globe in 10 seconds, what value should I set the `autoRotateSpeed` to?

**Comment by duytk7** [comment]
You can check here [ThreeJs]( https://threejs.org/docs/#examples/en/controls/OrbitControls)

**Comment by idjuradj** [comment]
This should solve my question. Thanks! @duytk7
