### ISSUE TITLE
Remove outline

### ISSUE THREAD

**Issue by benjaminlim00** [vasturiano/react-globe.gl#16]
Is your feature request related to a problem? Please describe.
Is it possible to remove the focus outline around the globe component?

I have tried using outline: none and focus: outline: none on the Globe component as well as it's parent component and it seems that I am not able to remove the outline using that.

**Comment by vasturiano** [comment]
@benjaminlim00 have you tried `showAtmosphere={false}`?

**Comment by benjaminlim00** [comment]
I was referring to this black outline here
![Screenshot from 2020-10-20 17-24-15](https://user-images.githubusercontent.com/36101433/96567249-26ad9980-12f9-11eb-8038-1df37e87b0f5.png)

**Comment by ilya-trifonov** [comment]
@benjaminlim00 add class to component with Globe, and use style:
```
.Globe * {
    outline: none;
}
```

**Comment by benjaminlim00** [comment]
Thank you for the response. I have tested it out, it does not work

**Comment by vasturiano** [comment]
@benjaminlim00 I've just pushed a fix that automatically removes the `outline` style from the component.
Can you try with `v2.12.6` and see if this solves it for you?

**Comment by benjaminlim00** [comment]
Yes i tested  it and the outline is removed! Thank you! I appreciate your help so much
