### ISSUE TITLE
How to disable pointer interaction

### ISSUE THREAD

**Issue by benjaminlim00** [vasturiano/react-globe.gl#18]
Is your feature request related to a problem? Please describe.
Hi, I would like to disable the pointer interaction such that the user cannot zoom into the globe nor drag around the canvas.

I have tried using the prop enablePointerInteraction and yet it does not work.

![Screenshot from 2020-10-21 13-28-51](https://user-images.githubusercontent.com/36101433/96677063-6203a300-13a1-11eb-9361-df63a32d5d77.png)

I have tried the following:

```
      enablePointerInteraction={[false]}
      enablePointerInteraction={false}
      enablePointerInteraction={()=>[false]}
      enablePointerInteraction={()=>false}
```

**Comment by vasturiano** [comment]
@benjaminlim00 you can disable the [orbit controls](https://threejs.org/docs/#examples/en/controls/OrbitControls.enabled), by accessing the `controls()` ref method. Something like:
```js
useEffect(() => {
  // assuming myGlobeRef exists and is assigned to the globe component
  myGlobeRef.current.controls().enabled = false;
}, [])
```

**Comment by benjaminlim00** [comment]
How about `enablePointerInteraction` ? What is it and how do I use it?

**Comment by benjaminlim00** [comment]
This solution does not work for me as it would also remove autoRotate from the globe

**Comment by vasturiano** [comment]
@benjaminlim00 `enablePointerInteraction` refers to click/hover events on the globe layers. Not the globe motion, that is controlled by the orbit controls mentioned above.

Perhaps you can selectively disable the parts of the controls that you don't need. You can check the [docs](https://threejs.org/docs/#examples/en/controls/OrbitControls).

For example:
```js
controls.enableZoom = false;
controls.enablePan = false;
```

**Comment by benjaminlim00** [comment]
thanks!
