### ISSUE TITLE
Remix 2.15 Window is not defined

### ISSUE THREAD

**Issue by Ebaq** [vasturiano/react-globe.gl#186]
Seems like it doesnt work on Remix. When refreshing the page shows this message.

Versions;
"three": "^0.171.0"
"react-globe.gl": "^2.28.3",

**Comment by vasturiano** [comment]
@ebaq this component is not compatible with SSR, it's meant to only be rendered in the browser, won't work on the server side. You can probably tell remix to not do any SSR for this component, and that should make it work.

**Comment by Ebaq** [comment]
@vasturiano Wow, thanks, forgot about ssr, my bad.
