### ISSUE TITLE
Unable to continually change globe point of view

### ISSUE THREAD

**Issue by benjaminlim00** [vasturiano/react-globe.gl#21]
**Describe the bug**
I am unable to continually change the globe's POV

So i have made a globe with labels data changing every 5 seconds. That is working fine and I would like to make the point of view be on that new location every 5 seconds.

I have succeeded in using 
`   const MAP_CENTER = { lat: 0, lng: 0, altitude: 1.5 };
    globeEl.current.pointOfView(MAP_CENTER, 0);`

to set the globe's initial POV. However when I try to change the POV every 5 seconds, this causes the globe to completely disappear
`
 useEffect(() => {
    const countryLocation = {
      lat: country.latitude,
      lng: country.longitude,
      altitude: 2.7,
    };
    globeEl.current.pointOfView(countryLocation, 0);
  }, [country]);
`

**Comment by vasturiano** [comment]
@benjaminlim00 it's hard to say without more context. Could you make a reproducing example on https://codesandbox.io/?

Also, have you verified that the coord values in your `countryLocation` are always defined?

**Comment by benjaminlim00** [comment]
Yes i have verified that. I am trying to make the globe work in codesandbox but I am having some difficulty

https://codesandbox.io/s/react-globe-4joch?file=/src/CustomGlobe.js

**Comment by benjaminlim00** [comment]
Not sure why, but it seems like all codesandbox examples of react-globe.gl are down
for example:
https://codesandbox.io/s/relaxed-hypatia-bocuz?file=/src/countryData.json

**Comment by vasturiano** [comment]
@benjaminlim00 I fixed a dependency conflict with `d3-geo` being duplicated, which was leading to the `d3-array` import issue in the sandbox. You can see the fix here: https://github.com/vasturiano/react-globe.gl/commit/3d754afbbe3e76b2f1895fa6cb6d02b175772ed0#diff-51e4f558fae534656963876761c95b83b6ef5da5103c4adef6768219ed76c2deL1169-L1175

If you use the latest version `2.12.9` the issue should be gone.

**Comment by benjaminlim00** [comment]
Thanks @vasturiano! I have done a example for the issue I am describing.
https://codesandbox.io/s/react-globe-4joch?file=/src/CustomGlobe.js:1577-1622

You can uncomment the line tagged with TODO to observe the error I am describing

**Comment by vasturiano** [comment]
@benjaminlim00 thanks for updating the codesandbox.

I logged your `countryLocation` structure and it seems to be missing the `lat`,`lng` attributes:
```js
{lat: undefined, lng: undefined, altitude: 2.7}
```

I think you're unstructuring your `selectedCountry` variable incorrectly, that's a single position array with different prop names:
```js
(1) [Object]
  0: Object
     lat: 35.907757
     lng: 127.766922
     label: "South Korea"
```

Another thing I would advise is to memoize your accessor functions as you pass them onto `Globe`.
This one in particular is problematic:
```js
hexPolygonColor={() => "#1b66b1"}
```
At every render the inner component will receive a new function reference, which will trigger all the hex polygons to have to be re-generated. Specially because this operation is rather heavy, it's causing a major performance impact on your app.
All you have to do is memoize the method. Something like:
```js
hexPolygonColor={useCallback(() => "#1b66b1", [])}

```

Hope this fixes all your issues. 😃

**Comment by benjaminlim00** [comment]
Thank you so much! I managed to get it working and I appreciate all your help :)

https://codesandbox.io/s/react-globe-4joch?file=/src/CustomGlobe.js

Right now I am able to get the POV to also be on each new country that pops up, but is there a way for me to smoothly do a transition from the original camera view instead?

**Comment by vasturiano** [comment]
On 
```js
globeEl.current.pointOfView(countryLocation, 0);
```

the second argument (`0`) is the transition time between locations. So just change that value to a positive value in milliseconds. 😃

**Comment by benjaminlim00** [comment]
Thank you for your assistance @vasturiano  :)
