### ISSUE TITLE
Disable globe zoom onScroll

### ISSUE THREAD

**Issue by iamanas20** [vasturiano/react-globe.gl#23]
Hello @vasturiano, thanks for an awesome globe library.

I'm trying to disable globe zoom when I scroll over it. Is there a way to do this?

I haven't seen anything related to this issue in the docs.

v2.13.0, MacOS Catalina

Thank you.

**Comment by shanewilson** [comment]
From what I can tell you need to access to the ref, the same way you would for adding auto-rotation:

```jsx
export const Globe = () => {
  const globeEl = useRef();

  useEffect(() => {
    globeEl.current.controls().enableZoom = false;
    globeEl.current.controls().autoRotate = true;
    globeEl.current.controls().autoRotateSpeed = 0.7;
  }, []);

  return <Globe ref={globeEl} ... />
```

**Comment by iamanas20** [comment]
Thanks Shane!

**Comment by md-ataur** [comment]
I am using  globe gl with next js but doesn't work on the next JS. Showing this message.
TypeError: Cannot read properties of undefined (reading 'controls').

export const Globe = () => {
  const globeEl = useRef();

  useEffect(() => {
    globeEl.current.controls().enableZoom = false;
    globeEl.current.controls().autoRotate = true;
    globeEl.current.controls().autoRotateSpeed = 0.7;
  }, []);

  return <Globe ref={globeEl} ... />

**Comment by Bawanthathilan** [comment]
> ```js
>  useEffect(() => {
>     globeEl.current.controls().enableZoom = false;
>     globeEl.current.controls().autoRotate = true;
>     globeEl.current.controls().autoRotateSpeed = 0.7;
>   }, []);
> ```

same

**Comment by Simoneth** [comment]
> md

Seems the same as this one:
https://github.com/vasturiano/react-force-graph/issues/333

**Comment by MohamedHesham1** [comment]
> > I am using globe gl with next js but doesn't work on the next JS. Showing this message. TypeError: Cannot read properties of undefined (reading 'controls').
> > ```
> > export const Globe = () => {
> >   const globeEl = useRef();
> > 
> >   useEffect(() => {
> >     globeEl.current.controls().enableZoom = false;
> >     globeEl.current.controls().autoRotate = true;
> >     globeEl.current.controls().autoRotateSpeed = 0.7;
> >   }, []);
> > 
> >   return <Globe ref={globeEl} ... />
> > ```
> 
> Looks like this one: [vasturiano/react-force-graph#333](https://github.com/vasturiano/react-force-graph/issues/333)
> 
> > I think you can get around this by moving the dynamic import to a wrapper file that includes both the ForceGraph3D (regular) import and the ref creation.
> 
> [Sandbox](https://codesandbox.io/s/nextjs-typescript-react-force-graph-3d-forked-cmq2n?file=/src/FocusGraph.tsx:527-983).
> 
> So, basically you have to create a wrapper file like:
> 
> ```
> import dynamic from 'next/dynamic';
> 
> const WrapGlobe = dynamic(import('./globe'), { ssr: false });
> 
> export default WrapGlobe;
> ```
> 
> Then create in the same folder another file called globe:
> 
> ```
> import { useRef, useEffect } from "react";
> 
> import Globe from "react-globe.gl";
> import data from "./data";
> 
> export default function GlobeComp() {
>     const globeEl = useRef();
> 
>     useEffect(() => {
>         console.log('here', globeEl?.current)
>     }, []);
> 
>     return (
>         <div>
>             <Globe
>                 ref={globeEl}
>                 ...
> ```
> 
> Tried in Next JS v.13


Thanks that did work.
