### ISSUE TITLE
Cannot Add Arcs to  arcsData

### ISSUE THREAD

**Issue by RomanBaiocco** [vasturiano/react-globe.gl#25]
**Describe the bug**
Once an arc is removed from `arcsData` no new arcs added to `arcsData` will be rendered

**To Reproduce**
Using this example: https://github.com/RomanBaiocco/react-globe.gl/blob/arcs_wont_update/example/arcs-bug/index.html
1. Go to the globe
2. Click on `REMOVE LINE` button on top left to remove arcs from `arcsData`.
3. See that the removed arcs disappear from the render.
3. Click on `RESET` to reset `arcsData` back to initial value.
4. See that the arcs that have been added back are not rendered.

**Expected behavior**
The arcs were added back to `arcsData` should be rendered. They are definitely back in `arcsData` as you have to press the remove button as many times as you did before to start removing the arcs that still remain on the globe.

**Comment by RomanBaiocco** [comment]
After some investigation, I'm pretty sure this issue goes all the way up to threeglobe

https://codesandbox.io/s/quirky-wave-cpfs1?file=/index.html
Heres a codesandbox with four buttons:
-One that clears `arcsData`
-One that reverts `arcsData` to its original value
-One that clears `pointsData`
-One that reverts `pointsData` to its original value

As you can see, you can clear and revert the points as much as you want, but once you clear the arcs, you can never revert.

**Comment by vasturiano** [comment]
Thanks for the report and for making the example @RomanBaiocco.

I've fixed this in the latest version `2.14.3`.
You were right that the issue was in `three-globe`. Basically some of the data object attributes weren't being cleaned up on removal. Which meant when the same arc objects were re-added to the graph some of the animations failed as they were trying to pick up from where it left off previously.

Your example should work correctly if you import the latest lib version.

**Comment by rohanbhangui** [comment]
@vasturiano I think I have a related issue. I have case where I am unmounting the globe component and remounting (simulate a react router route change). And I noticed the arcs seem to speed up. I don't think this is specific to `react-globe.gl`. I have seen this behaviour all the way down to `three-globe`. Some cases on remount they don't even render. Any ideas? Provided an example below of the speed increase

https://codesandbox.io/s/great-tamas-l9e2b8?file=/src/App.tsx
