### ISSUE TITLE
How to make a Transparent Globe

### ISSUE THREAD

**Issue by Drosaca** [vasturiano/react-globe.gl#29]
i don't know if it's a bug or not but i'm trying to turn the globe transparent like this. 
![image](https://user-images.githubusercontent.com/36480154/107724812-06a94800-6ce5-11eb-9a75-a70deb9bf920.png)

I found the same issue here in the pure js version
https://github.com/vasturiano/globe.gl/issues/20
when i tried this solution using react the globe has become entirely the same color as the background 

here is the code 

```js
     const img = require('./assets/test.png')
    const globeE1 = useRef();
    useEffect(() => {
        const globeMaterial = globeE1.current.globeMaterial();
        globeMaterial.opacity = 0;
    }, [])
    return (
        <div >
            <Globe
                ref={globeE1}
                globeImageUrl={img.default}
                backgroundColor={'rgba(255, 255, 255, 12)'}
                animateIn={true}
                showAtmosphere={false}
                height={400}
                width={400}
            />
```
thanks for help

**Comment by vasturiano** [comment]
Thanks for reaching out Pedro.

You were certainly on the right track here. Your code essentially made the complete globe surface transparent, which means you were just seeing through to the background.

It seems that what you wanted was to add some shapes marking the land portions of the earth. And for that, you need to use the polygons layer, and load in geo data about the land shapes.

I've put together a simple example that does exactly that, by loading in topo json data from [world-atlas](https://github.com/topojson/world-atlas).

Here's the [hollow globe example](https://vasturiano.github.io/react-globe.gl/example/hollow-globe/).
And the [example source](https://github.com/vasturiano/react-globe.gl/blob/master/example/hollow-globe/index.html).

**Comment by Drosaca** [comment]
Thanks for your answer,

In your example you used a shape inside a json to create the hollow effect but I'm wondering if it's possible to get the same effect using a png image to wrap the globe and edit the material properties in order to respect the alpha values from the image ?

**Comment by vasturiano** [comment]
Yes, you could certainly do that too, using the globe material [alphaMap](https://threejs.org/docs/#api/en/materials/MeshPhongMaterial.alphaMap).

If you do have a px map of just the earth land, this would probably be the most performant manner to achieve your goal, even though drawing the polygons looks ok performance wise.
