### ISSUE TITLE
Make globe component inherit width and height from parent element

### ISSUE THREAD

**Issue by kangah-codes** [vasturiano/react-globe.gl#34]
**Is your feature request related to a problem? Please describe.**
When creating responsive globes for devices with smaller screens it becomes quite complicated setting the width and height of the globe component. 

**Describe the solution you'd like**
I'd like the width and height props of the globe component to be either number or strings so in instances when a responsive globe is needed I can just set the width like ```width="100%"```

**Describe alternatives you've considered**
I have tried setting the width and height using strings, ie. ```width="100%"```. I have also tried to use refs to get the width and height of the parent element of the Globe and using hooks to set the width and height of the Globe, however this solution becomes more complex when taking into account responsiveness. Or I would like to know if there are any workarounds currently being used to achieve this outcome. Thanks

**Comment by vasturiano** [comment]
@kangah-codes you can just use a 3rd party lib to make any sizeable chart responsive, for example: [react-sizeme](https://github.com/ctrlplusb/react-sizeme).

**Comment by kangah-codes** [comment]
Thanks! I'll check that out

**Comment by iDVB** [comment]
Any chance we can get an example of how this would work @vasturiano?
I think the effect some are going for is that the globe would get smaller with the canvas.... not just crop the globe. 
This way it can be used on Desktop and Mobile.

**Comment by iDVB** [comment]
Thanks!

**Comment by DENNIS-CODES** [comment]
any other way of making the globe canvas responsive across all devices without using a react deprecated package 
example: [react-sizeme](https://github.com/ctrlplusb/react-sizeme)
the package was last published in 2021 and installing it today in next js would cause alot of incompatible issues

**Comment by ankurCES** [comment]
Found another way to work around this.
`const globeContainerRef = React.useRef<any>(null);

const [width, setWidth] = useState(0);
const [height, setHeight] = useState(0);
  useEffect(() => {
    const { offsetWidth, offsetHeight } = globeContainerRef.current;
    setWidth(offsetWidth);
    setHeight(offsetHeight);
}, []);

<div ref={globeContainerRef} style={{ width: '100%', alignContent: 'center'}}>
          <Globe
            ref={globeRef}
            globeImageUrl="//unpkg.com/three-globe/example/img/earth-blue-marble.jpg"
            bumpImageUrl="//unpkg.com/three-globe/example/img/earth-topology.png"
            backgroundImageUrl="//unpkg.com/three-globe/example/img/night-sky.png"
            width={width}
            height={height}
          />
</div>`

This allows to set the width as per the container
