### ISSUE TITLE
Altitude of the starting or ending point of an arc

### ISSUE THREAD

**Issue by JulesLassara** [vasturiano/react-globe.gl#36]
I have on my globe some custom layer in orbit, I would like to create some arc which starting (or ending) at a specific altitude. Do you know how can I do ? the property "arcAltitude" doesn't help, it changes only the max height of the arc.

**Comment by vasturiano** [comment]
@JulesLassara I haven't thought of use cases where you'd need the arcs to start/end anywhere other than the ground. So it's not currently supported, but could potentially be added as a feature, via two props like `arcStartAltitude` and `arcEndAltitude`.

Out of curiosity what type of data are you representing that asks for this representation?

**Comment by JulesLassara** [comment]
That would be perfect !! I'm using it to represent some satellites and some data traffic between users and satellites, just for fun at the moment, I'm passionate about all constellations (like Starlink for example)

**Comment by vasturiano** [comment]
@JulesLassara that sounds cool. Well, keep in mind that you can do the same with the `pathsLayer`. That lets you specify `lat`, `lng` and `alt` for each of the points in the path, which actually might be better suited for your use case than the arcs.

Check out the docs: https://github.com/vasturiano/react-globe.gl#paths-layer

**Comment by JulesLassara** [comment]
Do you know @vasturiano how to use the pathsLayer by keeping the same data format as arcs for that ?
I can't find a good way to display my links between 2 points only, basically I have my starting and ending coordinates in a JSON object for each link.

**Comment by vasturiano** [comment]
@JulesLassara sure, you should be able to configure the data accessor properties to adjust to your syntax. You just need to generate an array of 2 points per link in your data.

So, assuming your data looks something like:
```js
const linksData = [
  { 
    start: { lat: 2, lng: 3, alt: 0.02 }, 
    end: { lat: 4, lng: -2, alt: 0 }} 
  },
  { 
    start: { lat: 5, lng: -5, alt: 0 }, 
    end: { lat: 23, lng: -4, alt: 0.3 }} 
  }
  ...
];
```

you can feed it to the paths layer via the accessors
```js
pathsData={linksData}
pathPoints={link => [link.start, link.end]} // a path array with 2 points
pathPointLat="lat"
pathPointLng="lng"
pathPointAlt="alt"
...
```

**Comment by JulesLassara** [comment]
Thank you so much. It seems easy now I understand how it works ! But is it normal that the path between 2 coordinates isn't the shortest at all ? Sometimes, the path is traveling all around the map.

**Comment by vasturiano** [comment]
@JulesLassara are some of your lines per chance crossing the anti-meridian (-180º/180º longitude)? That could be one reason why you would see the long way around path. Those cases can be tricky to represent.

**Comment by JulesLassara** [comment]
I think so yes because it's travelling all around the globe. Thank you for your answer!!!

**Comment by vasturiano** [comment]
For those cases, you can try to extend the longitudes beyond their -180/180 limit, so that the difference between them is minimal. 

For example, if you have two points like this:
`{ startLng: 178, endLng: -177 }`
change them into:
`{ startLng: 178, endLng: 183 }`

Hopefully that fixes it.

**Comment by JulesLassara** [comment]
That was it ! Thank you for all. (btw I had some bad coordinates too, with +300 longitude haha)

Have a wonderful day !
