### ISSUE TITLE
How to change the atmosphere color

### ISSUE THREAD

**Issue by gbreux** [vasturiano/react-globe.gl#37]
Hi, 

I have 3 questions about this amazing library (thank you!)

- Is it possible to change the atmosphere blueish color?
- I'm using the tile feature but I was wondering how I can display a tile only when I hover it and mask the rest by default?
- Is it possible to pause the globe rotation when we hover it?

I hope it's possible!

Thanks

**Comment by vasturiano** [comment]
@gbreux thanks for reaching out.

1. it is not currently possibly to change the atmosphere color, it is hard coded. But I think it could be a useful addition, I'll leave this issue open until I have a little bit of time to implement it. 👍
2. you can perform the action to change the tile material (from transparent to visible for example) on the event callback of `onTileHover`.
3. similarly, you can disable the globe auto-rotation (`globeRef.current.controls().autoRotate = false`) on whichever event you'd like to tie it to, for example `onTileHover` like above.

**Comment by gbreux** [comment]
Thanks @vasturiano for the hints!

1.  That would be nice yes 🙏 
2. May I ask for a sample? `tile.material = new THREE.MeshLambertMaterial({ color: "red", opacity: 1 })}` doesn't seem to work 🤔 Also, how would I now when the mouse leave a tile to make them transparent again?
3. The issue I have with this solution is how would you reactivate the rotation when your mouse leave the globe?

**Comment by vasturiano** [comment]
Hi @gbreux 

1. I've just implemented this functionality, so you can do `atmosphereColor="purple"`. It also supports the atmosphere width via `atmosphereAltitude={0.3}`. Please try with the latest component version.
2. You need to access to three object itself, available under the `__threeObj` attribute. And when the hover is finished, you will receiver another `onTileHover` event with a `null` parameter, indicating the pointer has left the hovered tile. Furthermore, the second parameter of the hover method indicates the previous value of the tile hover. Putting all this together you can do:
```js
onTileHover((tile, prevTile) => {
  if (tile) { // tile hover in
    tile.__threeObj.material.opacity = 1;
  }
  if (!tile && prevTile) { // tile hover out
    prevTile.__threeObj.material.opacity = 0;
  } 
}
```
3. Just like the above you can resume the rotation when you detect the end of the hover, by observing a `null` parameter.

**Comment by gbreux** [comment]
Awesome for the atmosphereColor, it works like a charm! 🎉 

Thanks 🙏
