### ISSUE TITLE
How to style the canvas element ?

### ISSUE THREAD

**Issue by MatteoGauthier** [vasturiano/react-globe.gl#39]
Hey i saw that props are not passed to children element, if it can be possible we can add className to the element

**Comment by vasturiano** [comment]
@MatteoGauthier `className` is generally not applicable to non-native React elements (like the `Globe` component).

If you want to style it, you should wrap it in a `div` and apply the styling there.
```js
<div className="foo">
  <Globe ... />
</div>
```

**Comment by MatteoGauthier** [comment]
> @MatteoGauthier `className` is generally not applicable to non-native React elements (like the `Globe` component).
> 
> If you want to style it, you should wrap it in a `div` and apply the styling there.
> ```js
> <div className="foo">
>   <Globe ... />
> </div>
> ```

Okay thanks you 👌
