### ISSUE TITLE
Initial Zoom

### ISSUE THREAD

**Issue by gbreux** [vasturiano/react-globe.gl#43]
Hi,

I'm looking to tweak a little bit the globe but couldn't find any solution.

- Is there a way to set a different initial zoom that will be used to generate the first load animation? (I found how to set a different zoom, but there is a glitch when it loads)
- Also, is there a way to decide where the globe will stop after the load animation ends? (if we pass a lng/lat coordinate)

Thanks!

**Comment by vasturiano** [comment]
@gbreux have you tried using `pointOfView` on component mount, as in the following example?
https://github.com/vasturiano/react-globe.gl/blob/8ca904ec72682da9d084dc5de9e6a6e7b2179e6e/example/airline-routes/us-international-outbound.html#L57-L60

**Comment by gbreux** [comment]
@vasturiano thanks, that would be the perfect solution indeed, but there is a glitch where the globe animate toward the animation at altitude 1 and once done, resize it to altitude 2 without transition.

**Comment by abdullah1572** [comment]
thanks man

**Comment by Thkasis** [comment]
Here's one with a shift of the globe included but might be less code and easier. 

import React, { useEffect, useRef } from 'react';
import Globe, { GlobeMethods } from 'react-globe.gl';

const World = () => {
    const globeEl = useRef(undefined);
    const w = window.innerWidth;
    const shiftFactor = 0.4;
    const shiftAmmount = shiftFactor * w;

    useEffect(() => {
        if (globeEl.current) {
            (globeEl.current as GlobeMethods).pointOfView({ lat: 41, lng: -95, altitude: 2.5 });
        }
    }, [globeEl]);

    return (
        <>
            <Globe
                width={w + shiftAmmount}
                onGlobeRightClick={(event) => console.log(event)}
                globeImageUrl='https://unpkg.com/three-globe@2.18.0/example/img/earth-blue-marble.jpg'
                bumpImageUrl='https://unpkg.com/three-globe@2.18.0/example/img/earth-topology.png'
                backgroundImageUrl="//unpkg.com/three-globe/example/img/night-sky.png"
                waitForGlobeReady={true}
                animateIn={true}
                showGlobe={true}
                ref={globeEl}
            />
        </>
    )
}

export default React.memo(World)
