### ISSUE TITLE
QUESTION: Rotation animation on globe click

### ISSUE THREAD

**Issue by gbreux** [vasturiano/react-globe.gl#47]
Hi!

I was wondering if there were a way to smoothly transition the globe rotation on a different coordinate ?

For example, manually changing the coordinates with `pointOfView({lat, lng})})` would make the globe rotate smoothly toward these coordinates.

Thanks!

**Comment by vasturiano** [comment]
@gbreux thanks for reaching out.

Yes, as described in the api docs, that method supports the animation time (in ms) as 2nd argument. So you can do:
```js
.pointOfView({ lat, lng }, 700)
```
