### ISSUE TITLE
QUESTION: High number of tiles

### ISSUE THREAD

**Issue by gbreux** [vasturiano/react-globe.gl#48]
Hi again :) 

I need to create a high number of tiles (10,000 only visible one at a time on hover) and I can start to feel some performance issue (especially on Safari).

Do you think of another solution than the traditional `tilesData` props?

Here is how I do it at the moment:

```
[...Array(80).keys()].forEach((latIdx) =>
  [...Array(125).keys()].forEach((lngIdx) =>
    arr.push({
      lng: -180 + lngIdx * (360 /  125) + 1.5,
      lat: 90 - latIdx * (180 / 80) - 1
    })
  )
);
```

```
onTileHover={(tile: any, prevTile: any) => {
    globeEl.current.controls().autoRotate = !tile;
  if (tile?.__threeObj) {
    tile.__threeObj.material = new materials.MeshLambertMaterial({
      color: "#c026d3",
      opacity: 0.6,
      transparent: true,
    });
  }
  if (prevTile?.__threeObj) {
    prevTile.__threeObj.material = new materials.MeshLambertMaterial({
      color: "#c026d3",
      opacity: 0,
      transparent: true,
    });
  }
}}
```

Thanks a lot for your help!

**Comment by gbreux** [comment]
The `pauseAnimation()` on scroll helped a lot already. 
But still, i'll take any advice :)

**Comment by vasturiano** [comment]
@gbreux have you tried simply changing the `opacity` attribute on the material, instead of creating a new one? Like this:
```js
onTileHover={(tile, prevTile) => {
  tile && (tile.__threeObj.opacity = 0.6);
  prevTile && (prevTile.__threeObj.opacity = 0);
}}
```

**Comment by gbreux** [comment]
I did, but for some reason, it changes all the tile's opacity, not just the selected one.

But even though, 10k tiles seems to be super heavy even without any hover event. The globe rotation animation lag a bit, it's not smooth (and it's worse on safari), hence my desire to find a lighter solution.

**Comment by vasturiano** [comment]
@gbreux if it's affecting all tiles, are you per chance sharing the same material object across all tiles with `.tileMaterial`?

Regarding your other approach with globeHover, you could possibly catch your own hover events on your container element, and then translate them into globe coordinates using `toGlobeCoords`.

**Comment by gbreux** [comment]
Indeed, I used the same object so that make sense.

Anyway, the `toGlobeCoords` trick works like a charm, thanks a lot! 🙏
