### ISSUE TITLE
[Question] How could I make the Github globe?

### ISSUE THREAD

**Issue by nandorojo** [vasturiano/react-globe.gl#49]
@vasturiano Just want to say that I'm absolutely amazed by this project. I've now seen incredible globes from Vercel, Stripe and GitHub, and I'm looking to implement a similar one.

Do you have a rough idea of how I would configure the globe to look like the one from [github.com](https://github.com)?

<img width="1792" alt="Screen Shot 2021-04-24 at 4 44 17 PM" src="https://user-images.githubusercontent.com/13172299/115972555-1501b480-a51d-11eb-9780-47efffef6d4b.png">

It seems like the data part is relatively straightforward, but I'm curious mostly about the design.

I also noticed that GitHub has image/video fallbacks in case it loads slowly or GL isn't supported(?) Do you have any suggestions for how to implement that. 

Thanks for your help and great contributions.

**Comment by nandorojo** [comment]
If it's easier, I'd also be interested in making one like the Vercel site:

![image](https://user-images.githubusercontent.com/13172299/115972627-817cb380-a51d-11eb-9504-aba4068b855f.png)

I don't want to take up too much of your time, but at the very least, just wanted to see if you have a general idea for which direction I should go in. In the meantime, I'll be playing with the lib and reading through the docs more.

**Comment by vasturiano** [comment]
@nandorojo thanks for reaching out.

Sounds like you should be able to get close to those designs using the various layer building blocks in this module. You have the Points layer for the dots, the Arcs layer for the links, and even the Hexed Polygons for the "pixelated" continents like in the GH globe.

**Comment by nandorojo** [comment]
I ultimately decided to go with the Vercel globe

![](https://user-images.githubusercontent.com/13172299/115972627-817cb380-a51d-11eb-9504-aba4068b855f.png)

Similarly, do you have pointers for what APIs to use to make there?
