### ISSUE TITLE
Data format of Polygons Layer ? 

### ISSUE THREAD

**Issue by Senelith** [vasturiano/react-globe.gl#5]
hi @vasturiano first of all Thanks for this amazing library. I couldn't find the exact data format that should be fed to the `polygonsData`  ? I'm trying to show some information in a label when the user clicks on a country on the globe. In order to do this I must fill the globe with the details of the countries. 
It would be a great help if i could have a simple codesandbox of this Polygonal layered globe

**Comment by vasturiano** [comment]
@Senelith thanks for reaching out.

There is a usage example here: https://github.com/vasturiano/react-globe.gl/blob/master/example/choropleth-countries/index.html

Basically, any array of objects can be passed onto `.polygonsData(<my polygons>)`. It should be one object per polygon. 

Then you set the accessor function `.polygonGeoJsonGeometry(polygonObj => polygonObj.geometry)` to the way to extract the polygon's coordinate specification from each object, in GeoJSON format. This defaults to the `geometry` attribute as is conventional in GeoJSON but you can modify that.

As per the docs for `polygonGeoJsonGeometry`:
> Polygon object accessor function or attribute for the GeoJson geometry specification of the polygon's shape. The returned value should have a minimum of two fields: type and coordinates. Only GeoJson geometries of type Polygon or MultiPolygon are supported, other types will be skipped.

**Comment by ilya-trifonov** [comment]
@vasturiano I need your help with Poligons visualisation.
I have some static data for all polygons:
```
export const Antenna1 = [
	{
		signal: 1,
		position: [
			{ lat: 54.1297, lng: -3.2712 },
			{ lat: 56.1832, lng: -9.832 },
			{ lat: 58.2617, lng: -20.2879 },
			{ lat: 58.6558, lng: -20.094 },
			{ lat: 59.1262, lng: -19.8553 },
			{ lat: 59.7803, lng: -19.5097 },
			{ lat: 60.9527, lng: -18.8471 },
			{ lat: 61.3319, lng: -18.62 },
			{ lat: 61.2814, lng: -18.6506 },
			{ lat: 58.031, lng: -3.8264 },
			{ lat: 56.1487, lng: 0.5961 },
			{ lat: 54.579, lng: 3.1844 },
			{ lat: 53.1632, lng: 5.0176 },
			{ lat: 51.9053, lng: 5.9027 },
			{ lat: 52.3616, lng: 1.7837 },
			{ lat: 54.1297, lng: -3.2712 },
		],
	},
...
]
```

I converted this data to: 
```
[
    {
        "type": "Feature",
        "properties" :  {
            "signal" :1
        },
        "geometry" : {
            "type": "Polygon",
            "coordinates" : [
                [54.1297, -3.2712],
                [56.1832, -9.832],
                [58.2617,-20.2879],
                ...
            ]
        }
    },
    ...
]
```

But have an error:

`Uncaught TypeError: state.polygonsData.forEach is not a function`

**Comment by vasturiano** [comment]
@ilya-trifonov difficult to say without more info. Could you make a simple reproducing example of your issue at https://codesandbox.io/ ?

**Comment by ilya-trifonov** [comment]
@vasturiano 
everything is working. I missed the square bracket after "coordinates"
