### ISSUE TITLE
korean label text crashes

### ISSUE THREAD

**Issue by C17AN** [vasturiano/react-globe.gl#50]
Thanks to your gorgeous library! 😁
But I think there's a problem with korean label support.

**Describe the bug**
![image](https://user-images.githubusercontent.com/26535030/116781682-7696c580-aabf-11eb-9b48-acb1d165d7f3.png)

**To Reproduce**
when I use LabelText as Other language, It goes to "??".

**Expected behavior**
Ex. "Vatican City" to korean, It should produce "바티칸 시", but it shows "??".

**Screenshots**
![image](https://user-images.githubusercontent.com/26535030/116781732-cb3a4080-aabf-11eb-861d-c2e298d0be9e.png)

**Desktop (please complete the following information):**
- Chrome, MacOS 10.15 (Catalina)

**Smartphone (please complete the following information):**

**Additional context**

**Comment by vasturiano** [comment]
Thanks for reaching out @C17AN.

Most likely that's because the [default font](https://github.com/mrdoob/three.js/blob/dev/examples/fonts/helvetiker_regular.typeface.json) doesn't support special characters.

You can see a similar case here: https://github.com/vasturiano/globe.gl/issues/26

**Comment by C17AN** [comment]
Thanks!! It perfectly works!!!

![image](https://user-images.githubusercontent.com/26535030/116804229-2cadee00-ab58-11eb-809d-dee60304f73e.png)
