### ISSUE TITLE
bumpImageUrl does not seems to work

### ISSUE THREAD

**Issue by lezan** [vasturiano/react-globe.gl#53]
**Describe the bug**
Image used in bumpImageUrl does not seems to be apply as bump up to globe.

**To Reproduce**
I cannot find any issue related on console, but just jeck my codesandbox.

**Expected behavior**
I expected to see bump texture applied to globe.

**Screenshots**
Just check [this](https://codesandbox.io/s/vasturiano-react-globegl-0c5rq) codesandbox to see it.

**Desktop:**
 - OS: Windows 10
 - Browser Mozilla Firefox 
 - Version v88, 64bit

I am not sure about it, but I cannot see any changes when I apply a bump texture (to be sure I used the same texture used [here](https://github.com/vasturiano/react-globe.gl/blob/master/example/custom-globe-styling/index.html) by you.

**Comment by vasturiano** [comment]
@lezan by looking at your sandbox the bumpmap is applied. It's a subtle effect but it should be there. If you switch off the `globeImageUrl` it becomes more obvious and you'll notice it's being applied.

**Comment by lezan** [comment]
Hello @vasturiano, thanks for you quickly answer.

You are right, that was my bad. Am I missing something or it is not possible to change (up and down) bump scale? Did you exposed `bumpbScale`?

Thanks.

**Comment by vasturiano** [comment]
@lezan no it's not exposed directly, but you can always customize various attributes of you globe wrapping material using `globeMaterial`, like in this example:
https://github.com/vasturiano/react-globe.gl/blob/8ca904ec72682da9d084dc5de9e6a6e7b2179e6e/example/custom-globe-styling/index.html#L21-L27

**Comment by lezan** [comment]
Hello @vasturiano.
That's a good idea!

Thanks as always for your support and libraries!
