### ISSUE TITLE
Is it possible to clear an already running animation?

### ISSUE THREAD

**Issue by mylesfarm** [vasturiano/react-globe.gl#55]
**Additional context**

I am animating my globe rotating slowly on page load, using `.pointOfView()` with a long, `35000` time value. When a user manually clicks the globe during this animation, the animation continues and ignores the user input.

I've tried calling `.pauseAnimation()` onClick, which does stop the animation, but also prevents further user input. I also tried calling a shorter `.pointOfView()` animation, but after that the globe continues to finish the 35 second spin.

Is there a recommended way of handling this situation? Thank you so much.

**Comment by vasturiano** [comment]
@mylesfarm thanks for reaching out.

If you'd like to have the globe auto-rotate endlessly, it is better to use the pattern in [this example](https://vasturiano.github.io/react-globe.gl/example/world-population/), by setting that config in the Orbit controls directly:
https://github.com/vasturiano/react-globe.gl/blob/ab2941f425888a9bc7919dfd8716ec68526ae961/example/world-population/index.html#L32-L36

Additionally, if you need to stop the auto-rotation at a certain point, you just need to set `controls.autoRotate = false`. 
For example, if you'd like to cancel it whenever the user touches the controls manually, you can do something similar to:
```js
const controls = globeEl.current.controls();
controls.addEventListener('start', () => controls.autoRotate = false);
```

You can read more about the Orbit controls API at: https://threejs.org/docs/#examples/en/controls/OrbitControls

**Comment by mylesfarm** [comment]
Thank you @vasturiano!
