### ISSUE TITLE
How to use a fixed light setup?

### ISSUE THREAD

**Issue by derwaldgeist** [vasturiano/react-globe.gl#56]
That's an amazing package, thanks for creating this! I'd like to modify the light setup, so the directional light won't rotate with the camera and the globe is always lighted from where the camera sits, even if I rotate it (=> "no dark side of the earth"). Is this possible somehow?

Coming from Unity, I am dearly missing a scene description, to get an understanding how this is set up and how I can modify it. I looked at globe.gl and three-globe.gl as well, but couldn't find a description of the scene there either.

I tried to manipulate the scene, by getting a reference to the globe object. First, I tried to remove the directional light, to see what happens. According to the Three.js docs, this light inherits from Object3D, so it should have a `removeFromParent()` method. However, I couldn't find such a method on the object. Is `react-globe.gl` hiding some functionality somehow?

**Comment by vasturiano** [comment]
@derwaldgeist thanks for reaching out.

You can access the scene object using the `scene()` component method (accessible via ref).
Once you have access to the scene you can perform any custom modifications you'd like using the [ThreeJs API](https://threejs.org/docs/#api/en/scenes/Scene).

If you'd like to attach a light source to the point of view you could try bundling it together with the camera as a group, or even handier perhaps add it as a child object of the camera (accessible directly via the `camera()` method for convenience).

To remove the existing directional light, you just need to find it by browsing the scene object tree (it's in one of the top levels), and then use either `remove` or `removeFromParent` to exclude it.

**Comment by derwaldgeist** [comment]
Awesome, thanks, will try that. Setting the light as a child of the camera makes sense.

**Comment by TheManFromEarth1** [comment]
@derwaldgeist would you be willing to share an example implementation of yours with fixed light for beginners?
