### ISSUE TITLE
Prevent Zoom

### ISSUE THREAD

**Issue by derwaldgeist** [vasturiano/react-globe.gl#58]
In our use-case, we want to prevent the users from zooming into the globe, since it would be too distracting. They should only be able to rotate it around. Is there a way to prevent zooming? I saw `onZoom` and tried to set it to `() => {}`, but this did not have an effect.

It would also be great if there was a way to limit the rotation to one axis (x in our case), so you can spin the globe like a physical globe, but not rotate it in both directions.

**Comment by vasturiano** [comment]
@derwaldgeist you can access the Orbit controls that are used for user interaction in navigating the scene, via the `controls()` component method.

From there you can modify its configuration to apply some restrictions. Look into the [Orbit controls API](https://threejs.org/docs/#examples/en/controls/OrbitControls) for more details.

For your specific use case, looks like you just need to set `enableZoom = false`, `maxAzimuthAngle = 0` and `maxPolarAngle = 0`.

**Comment by derwaldgeist** [comment]
Awesome, thanks for the info!

**Comment by derwaldgeist** [comment]
Tried it out. Restricting the zoom worked, that's awesome. Restricting the `maxPolarAngle` did not work, however, because it restricts the globe from being rotated in the x direction (I need to lock the y axis). `maxAzimuthAngle = 0` did not have a visible effect.

**Comment by vasturiano** [comment]
Ah right. To lock the latitude rotation, you should lock the polar angle to the equator (in radians):
```js
controls.minPolarAngle = controls.maxPolarAngle = Math.PI / 2;
```

The azimuth is relative to the longitudinal direction, which is your intention to leave unrestricted if I understand correctly.

**Comment by derwaldgeist** [comment]
Hey, this works perfectly, thanks!

**Comment by woobinpro** [comment]
please send me some example codes
