### ISSUE TITLE
Request: onGlobeRotate event

### ISSUE THREAD

**Issue by derwaldgeist** [vasturiano/react-globe.gl#60]
I'd like to react, if the user rotates the globe by dragging it around. For this, it would be ideal to have an `onGlobeRotate` event. Ideally, this should report the angles of the rotation, as well as the lat/lon of the point in the center of the view (and/or maybe the bounding box of the visible part of the globe).

(I saw that the OrbitControls have a `change` and an `end` event. This at least gives me notice if something has changed).

**Comment by vasturiano** [comment]
@derwaldgeist the `onZoom` gives this functionality exactly as you mention. It also reports information on the point of view: `{ lat, lng, altitude }`.

You can easily test it by doing:
```js
onZoom={console.log}
```

**Comment by derwaldgeist** [comment]
Ah, awesome, will try it out! Hope this works, because I actually disabled the zoom.

**Comment by derwaldgeist** [comment]
Works perfectly, thanks again. Totally missed that!

**Comment by derwaldgeist** [comment]
I noticed an odd behavior of `onZoom`: If I debounce it using `lodash.debounce`, the debounced version still fires twice. It is as if `onZoom` fired a last event after a series of rotations, once the globe has stopped. Could that be?

**Comment by derwaldgeist** [comment]
It works with a higher timeout (500).

**Comment by derwaldgeist** [comment]
Ok, I now see why this long delay happens: The globe fires `onZoom` much longer after the (perceivable) rotation has already stopped.

**Comment by vasturiano** [comment]
Yes, because of controller inertia, which you can disable via [enableDamping](https://threejs.org/docs/#examples/en/controls/OrbitControls.enableDamping) if you'd like.
