### ISSUE TITLE
Responsive Example

### ISSUE THREAD

**Issue by lramos15** [vasturiano/react-globe.gl#62]
Thanks for the great library 👍 . I was wondering if there was any examples of the globe working in a place where responsive components are needed such as across devices. My globe canvas is too large and therefore on smaller devices push the contents off the screen as it is drawn over them. I'm not sure how to fix this and see most examples just have the globe taking up the entire screen and therefore aren't affected by this problem.

**Comment by vasturiano** [comment]
@lramos15 please see https://github.com/vasturiano/react-globe.gl/issues/34.
