### ISSUE TITLE
can not compile because of the new Three release (0.132.0)

### ISSUE THREAD

**Issue by TaylanDurmaz** [vasturiano/react-globe.gl#65]
Three version 0.132.0 just arrived and brokes this package. 
This happens because globe-gl requires:
...
        "three": ">=0.118 <1",
...
it downloads the latest version after 0.118

**Comment by vasturiano** [comment]
@TaylanDurmaz ok thanks. I've just applied a new update that should fix the issue. Could you please upgrade and let me know if you still experience any issues?

**Comment by TaylanDurmaz** [comment]
It is fixed now :) thanks!!
