### ISSUE TITLE
Attempted import error: 'TextBufferGeometry' is not exported from 'three'.

### ISSUE THREAD

**Issue by thaume** [vasturiano/react-globe.gl#68]
Hello ! Thanks for this awesome repo, I've learnt a lot of three.js related things 😅

Although I'm having a problem when trying to include the globe in my React project.

When starting my react app (with yarn) the compile step breaks with this error 

```
./node_modules/globe.gl/node_modules/three-globe/dist/three-globe.module.js
Attempted import error: 'TextBufferGeometry' is not exported from 'three'.
``` 

I've tried to force Three.js to version 0.132.0 but it didn't change anything. Let me know if you need more info to figure this out ! Happy to debug it further

**Comment by vasturiano** [comment]
Thanks for the report @thaume!

This import issue has now been fixed. It was due to a breaking change in `v133` of Three, which your build automatically included. 

All you should need to do is upgrade your dependency tree, specially of `three-globe`, which is where the fix took place. Make sure you have at least version `2.18.10` of that package, if using the latest version of `three`.

**Comment by thaume** [comment]
Thanks for the quick reply, I'll update right now and let you know how it goes !

**Comment by thaume** [comment]
Everything is working, I just had to add the latest version of three-globe and clean the yarn cache 👍

Thank you again !

**Comment by mehulappinessworld** [comment]
Same Error Not Solved Using Above Solution

**Comment by krono999** [comment]
the error persist, i cant add my own model to a existing projects, just appears this error

**Comment by vasturiano** [comment]
Could you make a reduced example on https://codesandbox.io that reproduces the issue?

**Comment by mehulappinessworld** [comment]
Now issue is solved

**Comment by healer-1205** [comment]
I try to use <textBufferGeometry> in react code.
But how can I import it?
<code>
import React from "react";
import textBufferGeometry from "three-globe";

const Education = ({ font }) => {
  return (
    <>
      <mesh rotation={[0, Math.PI, 0]} position={[40, 0.5, 90]}>
        <textBufferGeometry
          attach="geometry"
          args={["Education", { font, size: 3, height: 1 }]}
        />
        <meshBasicMaterial attach="material" color="#fafafa" metalness={1} />
      </mesh>
      <group>
        <mesh
          rotation={[Math.PI / 2 - Math.PI / 8, Math.PI, 0]}
          position={[35, 0.1, 84]}
        >
          <textBufferGeometry
            attach="geometry"
            args={["DCRUST", { font, size: 1, height: 0.1 }]}
          />
          <meshBasicMaterial attach="material" color="#fafafa" metalness={1} />
        </mesh>
        <mesh rotation={[Math.PI / 2, Math.PI, 0]} position={[37, 0.1, 81]}>
          <textBufferGeometry
            attach="geometry"
            args={[
              "B.Tech ECE \n Aug 2018-2022",
              { font, size: 1, height: 0.1 },
            ]}
          />
          <meshBasicMaterial attach="material" color="#fafafa" metalness={1} />
        </mesh>
      </group>
      <group>
        <mesh
          rotation={[Math.PI / 2 - Math.PI / 8, Math.PI, 0]}
          position={[40, 0.1, 72]}
        >
          <textBufferGeometry
            attach="geometry"
            args={[
              "R.S. Public Sr. Sec. School",
              { font, size: 1, height: 0.1 },
            ]}
          />
          <meshBasicMaterial attach="material" color="#fafafa" metalness={1} />
        </mesh>
        <mesh rotation={[Math.PI / 2, Math.PI, 0]} position={[37, 0.1, 69]}>
          <textBufferGeometry
            attach="geometry"
            args={["Karnal, Haryana", { font, size: 1, height: 0.1 }]}
          />
          <meshBasicMaterial attach="material" color="#fafafa" metalness={1} />
        </mesh>
        <mesh rotation={[Math.PI / 2, Math.PI, 0]} position={[37, 0.1, 66]}>
          <textBufferGeometry
            attach="geometry"
            args={["Class X and XII ", { font, size: 1, height: 0.1 }]}
          />
          <meshBasicMaterial attach="material" color="#fafafa" metalness={1} />
        </mesh>
      </group>
    </>
  );
};

export default Education;

</code>


This is current code
