### ISSUE TITLE
onPolygonClick won't trigger

### ISSUE THREAD

**Issue by maschad** [vasturiano/react-globe.gl#7]
**Describe the bug**
When performing a left click `onPolygonClick` is not called. I do notice however the function is called when the `onPolygonRightClick` prop is passed and triggered.

**To Reproduce**
1. Create an instance of `Globe` Element.
2. Ensure `polygonsData` is correctly populated.
3. Pass function to `onPolygonClick` prop.
4.Attempt to call `onPolygonClick` by left-clicking 

**Expected behavior**
The function passed as a parameter should be executed.

**Additional context**
Here's an example of the instance.
```javascript
	<Globe
			ref={globeEl}
			globeImageUrl='//unpkg.com/three-globe/example/img/earth-night.jpg'
			backgroundImageUrl='//unpkg.com/three-globe/example/img/night-sky.png'
			polygonsData={countries.features}
			polygonAltitude={d => (d === hoverD ? 0.12 : 0.06)}
			polygonCapColor={d => (d === hoverD ? "green" : "black")}
			polygonSideColor={() => "rgba(0, 100, 0, 0.15)"}
			polygonStrokeColor={() => "#111"}
			polygonLabel={({ properties: d }) => getPolygonLabel(d)}
			onPolygonHover={setHoverD}
			onPolygonClick={polygon => global.console.log("polygon", polygon)}
			polygonsTransitionDuration={300}
		/>
```

**Comment by vasturiano** [comment]
Hi @maschad you have a small mistake in the prop name, it should be `onPolygonClick` instead of `onHexPolygonClick`. 😃

**Comment by maschad** [comment]
Hey @vasturiano my apologies for the error in the code snippet, I will edit it, I had changed the prop to see if that one was working... 😪. But unfortunately I am still experiencing the issue.

**Comment by vasturiano** [comment]
@maschad I've just tried adding this prop to the [choropleth example](https://vasturiano.github.io/react-globe.gl/example/choropleth-countries/), and it seems to work fine:
```
onPolygonClick={polygon => console.log('polygon', polygon)}
```

Do you see any errors in your console?

**Comment by maschad** [comment]
@vasturiano  so I based my implementation off that example actually :) , but when I click nothing appears in the console. For further clarity, I am using **MacOS 10.15.3** and **Chrome Version 80.0.3987.149 (Official Build) (64-bit)**. Below is a screenshot of my console, but I believe the warnings are unrelated. 

![image](https://user-images.githubusercontent.com/9755286/78268992-9af42d00-74ce-11ea-9133-33ba5085b90d.png)

**Comment by vasturiano** [comment]
@maschad would you mind creating an example on https://codesandbox.io/ that reproduces the issue so we can debug further?

**Comment by maschad** [comment]
Thanks for responding so quickly @vasturiano 👍  , I'm sorry I took so long, I didn't see the notification on my github app 😩  , but yah let's take a look here https://codesandbox.io/s/relaxed-hypatia-bocuz for further clarity I am using it on one of my COVID19 apps right [here](https://github.com/maschad/covid19-banned-flights/blob/57d4da17e99442ffacbbdeecab083c15e3503e9c/src/components/MapChart.js#L44)

**Comment by vasturiano** [comment]
@maschad thanks for making the example. Your data file is empty so it's throwing an import error, but once it's past that I can see logs appearing in the console on click. Let me know if you observe the same.

**Comment by maschad** [comment]
Hey @vasturiano sorry about that it seems like there was some issue with the uploading of the file, regardless  I am still not seeing the logs appearing for me.
![Screen-Recording-2020-04-03-at-3](https://user-images.githubusercontent.com/9755286/78402970-2a7a0880-75c1-11ea-8e61-0952f8063619.gif)

**Comment by vasturiano** [comment]
@maschad I fixed the data file to get the example running. I'm still unable to reproduce that issue. I made a new codesandbox, could you try it here? https://codesandbox.io/s/angry-swartz-dzlhj

**Comment by maschad** [comment]
Ok, I think I have figured out the issue, I believe it's related to the different types of clicks that you have on the Mac Trackpad.  It works on **tap-to-click** but not on **force-click**, I was doing the latter. Thanks for your assistance though you have been very helpful. I am not sure if this is an issue you think is worthwhile addressing though.

**Comment by maschad** [comment]
I also notice that on mobile I have to do a sort of double tap which is inconsistent as well.

**Comment by vasturiano** [comment]
Ah, good catch! I believe the effect is mainly due to the auto-rotation of the globe. If you click down and hold (such as force clicking down on the mac pad) it is interpreted as a drag because the globe is moving. And drag interactions intentionally do not trigger click events.

I think the best way to handle this is to cancel the globe rotation as soon as the user drags the canvas, which signals the intent to control the globe, and the default motion should be let go off.

You can do that by adding an event handler to the controls `start` interaction:
```
globeEl.current.controls().addEventListener('start', () => world.controls().autoRotate = false);
```

Let me know if that works for your use case.

**Comment by maschad** [comment]
Yes that was the issue :) Thanks so much for your help, I am going to have to devise a way to get auto-rotate integrated and still not require the user to click twice. I'll let you know what I come up with.

**Comment by maschad** [comment]
This issue should be closed

**Comment by fgmorabito** [comment]
@vasturiano hi! it's possibile to click in automatic, something like " world.onPolygonClick(polygon,MAP_CENTER);" ?

thanks
Francesco
