### ISSUE TITLE
(Question) Getting lat/lng within onHexPolygonClick

### ISSUE THREAD

**Issue by narenranjit** [vasturiano/react-globe.gl#72]
The `onGlobeClick` callback receives a point argument from which I can get a lat/long. However, if I also have a hexPolygon layer the `onHexPolygonClick` only gives me polygon co-ordinates; is there a way to convert this to a lat/long also?

Alternatively, if I could "pass through" clicks from the hexPolygon layer and have the globe click handler detect it, that should also work, but the following seems to not be doing that either.

```
    pointerEventsFilter={(obj, data: any) => {
        return !(data?.geometry?.type === 'Polygon')
      }}
```

**Comment by narenranjit** [comment]
Hm, this seems intentional. Is there a reason to not also pass back the point object to the other event handlers?
```
if (objType === 'globe') {
        // include click coords in { lat, lng }
        var _this$toGeoCoords = _this.toGeoCoords(point),
            lat = _this$toGeoCoords.lat,
            lng = _this$toGeoCoords.lng;

        args.unshift({
          lat: lat,
          lng: lng
        });
      }
```

**Comment by vasturiano** [comment]
@narenranjit thanks for reaching out.

I've added the clicked coordinates to these click events. You can find them as the third argument of the `onHexPolygonClick` event callback.

Please update to the latest version of this module.

**Comment by narenranjit** [comment]
Thanks, this worked great! Appreciate the quick fix.
