### ISSUE TITLE
geojson file not rendering properly with Polygons Layer

### ISSUE THREAD

**Issue by bhbae123123** [vasturiano/react-globe.gl#75]
**Describe the bug**
Ultimately, I am trying to generate a globe full of grids, much like the [Tiles Layer example](https://globe.gl/example/tiles/), but have the animation (color, elevate on hover) of [Polygons Layer setup](https://vasturiano.github.io/react-globe.gl/example/choropleth-countries/). As a solution, I decided to create a geojson file that splits up the globe into small, equal-sized tiles and create a Polygons Layers react-globe.

I generated a geojson file and followed the [example setup](https://github.com/vasturiano/react-globe.gl/blob/master/example/choropleth-countries/index.html). It seems like `react-globe.gl` is registering the inverse of the areas outlined in my `features`' `polygon` geometry objects. Because of this, my colors are inversed and hover is very buggy. See example:
<img width="857" alt="Screen Shot 2022-01-26 at 11 02 46 PM" src="https://user-images.githubusercontent.com/30609213/151308122-3e6bf540-3fc2-4394-9176-f5cfe5346089.png">
<img width="835" alt="Screen Shot 2022-01-26 at 11 02 52 PM" src="https://user-images.githubusercontent.com/30609213/151308124-0b53264a-9ed7-4987-92e4-21944c8057a1.png">

I verified in geojson.io that my geojson does indeed look correct (please find my geojson file below):
<img width="839" alt="Screen Shot 2022-01-26 at 11 04 14 PM" src="https://user-images.githubusercontent.com/30609213/151308262-71855753-5db5-4101-ae3f-5291d5ea0600.png">

**To Reproduce**
I have the following code:
```typescript
import { useState } from "react";
import Globe from "react-globe.gl";
import pandora from "../shared/map.json";

type Feature = {
  bbox: Array<number>;
  properties: { addr: string };
  geometry: { type: string; coordinates: Array<Array<number>> };
};

export default function MyGlobe() {
  const [hoverAddr, setHoverAddr] = useState<Feature | undefined>(undefined);

  return (
    <Globe
      lineHoverPrecision={0}
      polygonsData={pandora.features}
      polygonAltitude={(d: Feature) => (d === hoverAddr ? 0.12 : 0.06)}
      polygonCapColor={(d: Feature) => (d === hoverAddr ? "steelblue" : "red")}
      polygonSideColor={() => "rgba(0, 100, 0, 0.15)"}
      polygonStrokeColor={() => "#111"}
      polygonLabel={(d: Feature) => `
        <b>addr: (${d?.properties?.addr})</b> <br />
      `}
      onPolygonHover={(polygon: Feature | null) => {
        setHoverAddr(polygon);
      }}
      polygonsTransitionDuration={300}
    />
  );
}
```

and my "../shared/map.json" is: 
```json
{
  "type": "FeatureCollection",
  "features": [
    {
      "geometry": {
        "type": "Polygon",
        "coordinates": [
          [
            [
              3,
              23
            ],
            [
              17,
              23
            ],
            [
              17,
              37
            ],
            [
              3,
              37
            ],
            [
              3,
              23
            ]
          ]
        ]
      },
      "type": "Feature",
      "properties": {
        "addr": "5,25"
      },
      "bbox": [
        3,
        23,
        17,
        37
      ]
    },
    {
      "geometry": {
        "type": "Polygon",
        "coordinates": [
          [
            [
              23,
              23
            ],
            [
              37,
              23
            ],
            [
              37,
              37
            ],
            [
              23,
              37
            ],
            [
              23,
              23
            ]
          ]
        ]
      },
      "type": "Feature",
      "properties": {
        "addr": "25,25"
      },
      "bbox": [
        23,
        23,
        37,
        37
      ]
    }
  ],
  "bbox": [
    -180,
    -90,
    180,
    90
  ]
}
```

I wrote a small python script to generate the geojson file. ^ is a smaller version of it, but with ^ geojson file, I still get the same issue. the python script I used to generate by geojson files:
```python
import json

dx = 10
dy = 10
gap = 3
flip = 0

geojson = {
  "type": "FeatureCollection",
  "features": [],
  "bbox": [
    -180,
    -90,
    180,
    90
  ]
}
for x in range(-180, 180, dx):
    for y in range(-90, 90, dy):
        flip += 1
        if flip % 2:
            continue
        print("{}, {}", x, y)
        feature = {
            "type": "Feature",
            "properties": { "addr": "{},{}".format(x+5, y+5) },
            "bbox": [x + gap, y + gap, x + dx - gap, y + dy - gap],
            "geometry": {
                "type": "Polygon",
                "coordinates": [
                    [
                        [ x + gap, y + gap ],
                        [ x + dx - gap, y + gap ],
                        [ x + dx - gap, y + dy - gap ],
                        [ x + gap, y + dy - gap ],
                        [ x + gap, y + gap ],
                    ]
                ]
            }
        }
        geojson["features"].append(feature)

with open('./src/shared/map.json', 'w') as f:
    json.dump(geojson, f, ensure_ascii=False)
```

**Expected behavior**
React-globe correctly registered the areas outlined in the geojson file and registers polygons as outlined. Hover elevates the polygon outlined by the geojson file only.

**Screenshots**
See in my description above

**Desktop (please complete the following information):**
 - OS: macOS Big Sur 11.4
 - Browser: Chrome
 - Version: Version 97.0.4692.99 (Official Build) (x86_64)

**Additional context**
Please find my additional context in my bug description

**Comment by vasturiano** [comment]
@bhbae123123 thanks for reaching out.

Your polygons may be reverse wound, which would lead to plotting the outer side of the globe.

Could you try and inverse the order of your coordinates, to see if you get a different result?

Just for some background info behind the winding direction, this module follows the convention used in [world-atlas](https://github.com/topojson/world-atlas), [natural earth](http://www.naturalearthdata.com/), [PostGIS](https://postgis.net/) and [D3](https://github.com/d3/d3-geo), since these are tools very frequently used to generate and handle geographical polygons. These tools all use the convention of _outer-boundary_: **clockwise** and _inner-holes_: **counter-clockwise**.

What is unfortunate is that this is the exact opposite of what the GeoJSON standard ([RFC 7946](https://datatracker.ietf.org/doc/html/rfc7946)) dictates. So there you have it, given the discrepancy between theory and practice, this repo makes the pragmatic decision to follow what's most commonly used.

You can see [here a comment](https://github.com/d3/d3-geo/pull/79#issuecomment-280935242) from _mbostock_ articulating some of the back story behind this.

**Comment by bhbae123123** [comment]
Reversing the order of my coordinates did the trick. TYSM!
