### ISSUE TITLE
Performance of: Hex bin layer on Chrome on Mac OS

### ISSUE THREAD

**Issue by benjazehr** [vasturiano/react-globe.gl#78]
**Describe the bug**
Using the latest version of Chrome 98.0.4758.102 and Mac OS 12.1 (21C52), the performance of hex bins is really bad.

**To Reproduce**
1. Go to the [world population example](https://vasturiano.github.io/react-globe.gl/example/world-population/)
2. Move the globe around
3. Check the FPS

**Expected behavior**
Moving the globe should feel more or less smooth. (In Firefox everything runs really well.)

**Screenshots**
![Bildschirmfoto 2022-02-22 um 15 49 40](https://user-images.githubusercontent.com/8629484/155157225-b5c5098a-4ac1-46f7-a2a7-4375daae0908.png)

**Desktop (please complete the following information):**
 - OS: Mac OS Monterey 12.1 (21C52)
 - Browser Chrome
 - Version 98.0.4758.102

Running on a MBP 15-inch, 2019, 2.6 GHz 6-Core Intel Core i7, 16 GB 2400 MHz DDR4

**Additional context**
In my team several people are using Chrome as their default browser and did not report the same performance issues last week. (Sorry that I cannot provide more detailed information about what version or time that was.)

**Comment by vasturiano** [comment]
@benjazehr thanks for reaching out.

I tried but was unable to reproduce your issue. I get close to 60fps on that example. My setup is very similar to yours, same exact Chrome version. Only difference is I'm on the newest `12.2.1` Monterey version, but I'd be surprised if that's the reason.

Do you get the same issue if you load the example in Incognito mode, or with all the extensions disabled? Perhaps one of them is interfering with the WebGL rendering.

**Comment by benjazehr** [comment]
Thank you very much for your quick response!

That's interesting. I just upgraded Mac OS to `12.2.1` but it didn't help.

Also running it in a Incognito window and disabling all the extensions did not improve it. I'm still at 10 fps and it feels even less responsive than that. 🤔

(Two colleagues of mine with different versions of Mac OS experience the problem. One other colleague with the latest Macbook Pro said it runs okay, but that computer has a lot of CPU power.)

Not sure if that helps, but this is how 3 seconds of recording "Performance" look like:

![Bildschirmfoto 2022-02-22 um 21 59 52](https://user-images.githubusercontent.com/8629484/155218916-e17e3b28-1b63-4651-8573-09f00f927369.png)

A lot of dropped frames (red ones).

When I inspect the Mac OS Activity Monitor I get 99.9% CPU usage for "Google Chrome Helper GPU". Safari and Firefox are both supersmooth and use not more than around 20% CPU.

**Comment by benjazehr** [comment]
Wow super interesting. I installed Chrome in Version `97.0.4692.99` [from here](https://google-chrome.en.uptodown.com/mac/versions) and everything ran smooth and perfect.

That means that it's in fact Chrome Versions `98.0.4758.XXX` that are causing problems.

**Comment by benjazehr** [comment]
In Chrome Version `98.0.4758.102` also the following examples are showing very bad responsiveness:

- <https://vasturiano.github.io/three-globe/example/hexbin/>
- <https://vasturiano.github.io/three-globe/example/labels/>

The other examples run really well – no problems at all.

**Comment by benjazehr** [comment]
Wow, this is so weird. We have multiple laptops here and suddenly all of them run super smooth again. I didn't change anything in my code, did not Update Chrome even (still on 98.0.4758.102) but the problem is just gone!

**Comment by benjazehr** [comment]
Getting close to the root of this misterious problem: The problem comes with a second screen. As soon as I disconnect my external screen from my laptop, my globe runs perfectly well (also in Chrome, FF and Safari have always worked well).

I've recorded a video to show the weird phenomenon:

- First: Situation in Chrome while external Screen (30" Thunderbolt Display), very laggy, not usable
- Second: Unplugging the external Screen
- Third: After a few seconds: super-smooth

https://youtu.be/Wuzmu92a1ck

I will close the issue now. As it's really only in a few globe-gl examples (labels/hexagons) and only on Mac OS and only in Chrome and only with external screens, this seems to be quite a niche problem.
