### ISSUE TITLE
Multiple arcs with their respective rings. 

### ISSUE THREAD

**Issue by PB-PDX** [vasturiano/react-globe.gl#80]
**Is your feature request related to a problem? Please describe.**
I am trying to figure out how I can implement rings at the end of an arc, much like the emit-arcs-on-click example except with more data/arcs. Instead of a click event, I would have data of start lat/lng and ending lat/lng and it would be in sequence. I have been able to  use the emit-arcs-on-click example to run arcs in sequence but the rings, thus far, trigger on render and then are removed. I am unsure of how to altar the rings behavior so they trigger after their respective arc. I would like the animation to show the arc and as that arc makes contact with the end lat/lng, the ring would initiate and then remove itself. Then the next arc and ring would do the same thing and so on. 

**Describe the solution you'd like**
A example of how this could be implemented. Your input wold be much appreciated. 

**Describe alternatives you've considered**
I have tried many ways of building an array of object to pass to the arcs/rings props. I have tried to combine them and played around with setTimeOut. The next thing I am going to try is to use an event listener perhaps. 

**Additional context**
The attached screen shot is the beginning of the animation. As you can see the arcs are triggering based on their timing but the rings are firing all at once.
![Screen Shot 2022-03-11 at 2 41 49 PM](https://user-images.githubusercontent.com/83720399/157984335-b009e29b-1644-4126-8149-aa46e6d02148.png)

**Comment by vasturiano** [comment]
@PB-PDX thanks for reaching out. What you are looking for appears to be just a variation of the [emit arcs on click example](https://vasturiano.github.io/react-globe.gl/example/emit-arcs-on-click/). Except that the triggers is not on click but supplying your own sequence data. That should change much of the underlying logic of creating and removing arcs and rings. Can you describe a bit more specifically which part you are having issues with? A reduced online example that focus just on the issue you're having would be beneficial too.

As for your attached screenshot, perhaps you just need to add a timeout for the target arcs addition, as in the example?
https://github.com/vasturiano/react-globe.gl/blob/8e7455cfde607ce481c4a91e33777004b676f071/example/emit-arcs-on-click/index.html#L43-L48

**Comment by PB-PDX** [comment]
Hi @vasturiano , thanks for the quick reply! Below is my current code. I added a timeout in the useEffect which does help with timing, but it seems to re-render each time which docks the performance quite a bit. Is there anyway you can see to improve this? Any help would be much appreciated. 
` 
 const [arcsData, setArcsData] = useState([]);
 const [ringsData, setRingsData] = useState([]);
 const [data, setData] = useState();
const [count, setCount] = useState(0);

const globeAnimation = () => {
    console.log('animate');
    const startLat = data[count].startLat;
    const startLng = data[count].startLng;
    const endLat = data[count].endLat;
    const endLng = data[count].endLng;
    const order = data[count].order;
    setCount(count + 1);

    // add and remove arc after 1 cycle
    const arc = { order, startLat, startLng, endLat, endLng };
    setArcsData((arcsData) => [...arcsData, arc]);
    setTimeout(
      () => setArcsData((curArcsData) => curArcsData.filter((d) => d !== arc)),
      FLIGHT_TIME * 2
    );

    // add and remove start rings
    const srcRing = { order, lat: startLat, lng: startLng };
    setRingsData((ringsData) => [...ringsData, srcRing]);
    setTimeout(
      () => setRingsData((ringsData) => ringsData.filter((r) => r !== srcRing)),
      FLIGHT_TIME * ARC_REL_LEN
    );

    // add and remove target rings
    setTimeout(() => {
      const targetRing = { order, lat: endLat, lng: endLng };
      setRingsData((ringsData) => [...ringsData, targetRing]);
      setTimeout(
        () => setRingsData((ringsData) => ringsData.filter((r) => r !== targetRing)),
        FLIGHT_TIME * ARC_REL_LEN
      );
    }, FLIGHT_TIME);
  };
  useEffect(() => {
    const timeout = setTimeout(() => {
      setCount(count + 1);
      globeAnimation();
    }, 6000);
    return () => {
      clearTimeout(timeout);
    };
  }, [count]);`

**Comment by PB-PDX** [comment]
@vasturiano , yes of course, here is the link to the sandbox: [https://codesandbox.io/s/react-globe-gl-arcs-with-rings-n2mxh0?file=/src/App.tsx](url) .

**Comment by vasturiano** [comment]
@PB-PDX thanks for creating the example.

I had a look and it seems what's really hurting the performance is the fact that a few props passed to the globe component are not being memoized across component re-renders. This tends to cause unnecessary repetitive internal updates because the prop values include different object references each time, which cause the component to think the value has changed. For example, if you turn this prop:
```jsx
hexPolygonColor={() => "#ffffff"}
```
into
```jsx
hexPolygonColor={useCallback(() => "#ffffff", [])}
```
you get an immediate massive gain in performance because suddenly the hexPolygonsLayer doesn't need to be re-computed each time.

The same should happen for all the other non-memoized functions, as well as `globeMaterial`, which is also regenerated at every render.

I believe if you update all those items you should end up with a pretty good performance on your globe.

**Comment by PB-PDX** [comment]
I appreciate all the help! Your suggestion made all the difference and now I am up and running.
