### ISSUE TITLE
Struggling to get the example to work

### ISSUE THREAD

**Issue by cryptobench** [vasturiano/react-globe.gl#81]
Hello. I'm trying to use the library inside my Nextjs project, but i'm struggling getting the basic example to work. 
I'm being met with the following error: [Screenshot](https://i.imgur.com/2WyVuiZ.png). What can I do to fix this issue?

**To Reproduce**
1) Install Nextjs
2) Create component

```
import Globe from "react-globe.gl"
import ReactDOM from "react-dom"

export default function Test() {
  return (
    <div>
      ReactDOM.render(
      <Globe pointsData={myData} />, myDOMElement );
      <div id="globe"></div>
    </div>
  )
}
```

**Comment by vasturiano** [comment]
@cryptobench looks like you're trying to use this module in SSR mode, which is not supported. The error you've shown is only the first of many you would encounter down that path.

Have a look at https://github.com/vasturiano/react-globe.gl/issues/1 for an idea on how to cancel the SSR in the import of this component.
