### ISSUE TITLE
PointLabel property or labelLabel property doesn't work for showing tooltip

### ISSUE THREAD

**Issue by steven3092** [vasturiano/react-globe.gl#91]
Hello,

I would like to show a tooltip when hover the bars on my globe but nothing appear when I check the code from volcanoes it seems to be easy you just pass  labelLabel={(d) => d.name} for example but nothing appear. 

How can I do ?

Regards

**Comment by vasturiano** [comment]
@steven3092 if you'd like to set tooltips on your points layer you should be using the `pointLabel` prop.

**Comment by steven3092** [comment]
Thanks for the quick reply but I've tried with the pointLabel prop but nothing appear. I've tried to set log too but same it's like the prop is frozen. I don't have html file, I am in pure js with react.

**Comment by vasturiano** [comment]
@steven3092 the best would be if you could make a reduced example on https://codesandbox.io/, so we can have a closer look.

**Comment by steven3092** [comment]
It works perfectly on the codesandbox, tomorrow I'll check out on my professionnal project whats wrong with what I did. At least now I have a personnal example working that I can use. Thanks a lot for your quick reply :)

**Comment by steven3092** [comment]
Hello,
I found where was the problem, it's because I use the library react sizeme for resizing the canvas as follow

```
<SizeMe>
                        {({ size: { width = 1400, height = 720 } }) => (
                          <Globe
                            globeImageUrl={globeUrl}
                            backgroundImageUrl={backgroundUrl}
                            width={width}
                            height={height}
                            pointsData={newMarkers}
                            pointRadius={0.30}
                            pointLat={d => d.lat}
                            pointLng={d => d.lon}
                            pointColor={d => d.color}
                            pointAltitude={d => d.normalizedValue}
                            pointLabel={getTooltip}
```

And doing like this, tooltips don't appear anymore or you have to set the width and height by default directly in the prop.
