### ISSUE TITLE
MaxDistance Not Working On All Browsers

### ISSUE THREAD

**Issue by 17x** [vasturiano/react-globe.gl#95]
minDistance with maxDistance are working quirks on diffrence browsers.

```
globeEl.current.controls().minDistance = 200;
globeEl.current.controls().maxDistance = 600;
```

both working on:
Monterey 12.1(intel) - Safari Version 15.2 (17612.3.6.1.6)
Monterey 12.3(apple silicon) - Safari Version 15.4 (17613.1.17.1.6)

only minDistance working on:
Monterey 12.1(intel) - Chrome Version 104.0.5112.101
Monterey 12.3(apple silicon) - Chrome Version 104.0.5112.101 (arm64)
Android 11(MIUI 12) - Chrome Version 104.0.5112.97

**Comment by vasturiano** [comment]
@17x thanks for your report.

I've pushed a patch that should fix this. If you upgrade your dependencies you should no longer notice this issue.

**Comment by 17x** [comment]
@vasturiano 
What a Great work !! You really saved my time.

For others who encountering same problem here, Remember delete your `node_modules` folder and re-install all packages.
